-- Drop table ACCESO
DROP TABLE IF EXISTS `ACCESO`;

CREATE TABLE `ACCESO` (
  `ACCESO_RUT` int(11) NOT NULL COMMENT 'RUT',
  `MOD_ID` int(11) NOT NULL DEFAULT '0',
  `FUNCION_ID` int(11) NOT NULL DEFAULT '0',
  `ACCESO_SW` int(11) COMMENT 'INDICA 1=ACCESA, 2=NO ACCESA',
  PRIMARY KEY(`ACCESO_RUT`, `MOD_ID`, `FUNCION_ID`),
  CONSTRAINT `Ref_69` FOREIGN KEY (`FUNCION_ID`, `MOD_ID`)
    REFERENCES `FUNCION`(`FUNCION_ID`, `MOD_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE=INNODB;