CREATE TABLE `cliente` (
  `CLI_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `CLI_NOM` varchar(300) DEFAULT NULL COMMENT 'Nombre',
  `CLI_EML` varchar(300) DEFAULT NULL COMMENT 'Email',
  `CLI_VIG` int(11) DEFAULT NULL COMMENT 'Vigencia',
  `CLI_FEC_ING` datetime DEFAULT NULL,
  `CLI_HRS_ING` datetime DEFAULT NULL,
  PRIMARY KEY (`CLI_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=latin1;

