DELETE FROM ESTUDIOS;
DELETE FROM EXPERIENCIA;
DELETE FROM OTROS;
DELETE FROM PORTAFOLIO;

DELETE FROM PROFESIONAL_PRODUCTO_VISITAS;
DELETE FROM PROFESIONAL_PRODUCTO_DENUNCIA;
DELETE FROM PROFESIONAL_PRODUCTO_PUNTUACION;
DELETE FROM PROFESIONAL_PRODUCTO_VOTACION;
DELETE FROM PROFESIONAL_PRODUCTO_CONTENIDO;
DELETE FROM PROFESIONAL_PRODUCTO;


DELETE FROM PUBLICACION_COMENTARIO;
DELETE FROM PUBLICACION_VOTACION;
DELETE FROM PUBLICACION_DENUNCIA;
DELETE FROM PUBLICACION_CONTENIDO;
DELETE FROM PUBLICACION_VISITAS;
DELETE FROM PUBLICACION_ETIQUETA;
DELETE FROM PUBLICACION_REFERENCIA;
DELETE FROM PUBLICACION_PROFESIONAL;
DELETE FROM PUBLICACION;

