<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src='js/jquery-1.10.1.min.js'></script>   
<script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>    
<script src='js/superfish.js'></script>
<script src='js/jquery.flexslider-min.js'></script>
<script src='js/jquery.mmenu.min.js'></script>
<script src='js/fancybox/jquery.fancybox.pack.js'></script>
<script src='js/contact.js'></script>
<script src='js/scripts.js'></script>
<script src="js/modernizr.js"></script>