<script src="../js/jquery.js"></script>
<script src="../js/bootstrap.min.js"></script>
<!--<script src="http://maps.google.com/maps/api/js?sensor=true"></script>-->
<script src="../js/owl.carousel.min.js"></script>
<script src="../js/mousescroll.js"></script>
<script src="../js/smoothscroll.js"></script>
<script src="../js/jquery.prettyPhoto.js"></script>
<script src="../js/jquery.isotope.min.js"></script>
<script src="../js/jquery.inview.min.js"></script>
<script src="../js/wow.min.js"></script>
<script src="../js/custom-scripts.js"></script>