CALL SP_CAT_CSU_COLECCION(@codErr);
SELECT @codErr;

-- SELECT * FROM PRODUCTO_CONTENIDO;

DROP PROCEDURE IF EXISTS bodyflex.SP_CAT_CSU_COLECCION;
CREATE PROCEDURE bodyflex.`SP_CAT_CSU_COLECCION`(OUT codErr INTEGER)
BEGIN
  
  DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;
  SET codErr=0;
  
  SELECT CP.COID 
  , (SELECT CONO FROM COLECCION C WHERE C.COID = CP.COID) AS COLECCION
  , CP.PROID
  , IFNULL(P.pcp1_id,0) AS CODCAT1
  , IFNULL((SELECT PCP1_NOM FROM PRODUCTO_CATEGORIA1 WHERE pcp1_id=P.pcp1_id),0) AS NOMCAT1
  , IFNULL(P.pcp2_id,0) AS CODCAT2
  , IFNULL((SELECT PCP2_NOM FROM PRODUCTO_CATEGORIA2 WHERE pcp2_id=P.pcp2_id),0) AS NOMCAT2
  , IFNULL(P.pcp3_id,0) AS CODCAT3
  , IFNULL((SELECT PCP3_NOM FROM PRODUCTO_CATEGORIA3 WHERE pcp3_id=P.pcp3_id),0) AS NOMCAT3
  , IF(P.pcp1_id IS NOT NULL AND P.pcp2_id IS NULL AND P.pcp3_id IS NULL, 1, 0) as TIPO1 -- 1 CATEGORIA 
  , IF(P.pcp1_id IS NOT NULL AND P.pcp2_id IS NOT NULL AND P.pcp3_id IS NULL, 1, 0) as TIPO2 -- 2 CATEGORIA 
  , IF(P.pcp1_id IS NOT NULL AND P.pcp2_id IS NOT NULL AND P.pcp3_id IS NOT NULL, 1, 0) as TIPO3 -- 3 CATEGORIA 
  FROM PRODUCTO P, COLECCION_PRODUCTO CP
  WHERE P.PROID = CP.PROID 
  GROUP BY CP.COID, NOMCAT1, NOMCAT2, NOMCAT3 
  ORDER BY CP.COID, NOMCAT2, NOMCAT3  ASC;
  
END




