
CALL SP_CP_ADM_CSU_BCO(@codErr);
SELECT @codErr;

DROP PROCEDURE IF EXISTS bodyflex.SP_CP_ADM_CSU_BCO;
CREATE PROCEDURE bodyflex.`SP_CP_ADM_CSU_BCO`(OUT codErr INTEGER) 
BEGIN
  
  DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;
  SET codErr=0;
  IF EXISTS(SELECT * FROM BANCOS) THEN
    SELECT BCONOM FROM BANCOS ORDER BY BCONOM ASC;
  ELSE
    SET codErr=98;
  END IF;
      
END




