
SELECT * FROM PUBLICACION_LIST_REFERENCIA;

CALL SP_CP_PRO_PUBLICACION_CONSULTA_REFERENCIA(@codErr);
SELECT @codErr;

DROP PROCEDURE IF EXISTS delta.SP_CP_PRO_PUBLICACION_CONSULTA_REFERENCIA;
CREATE PROCEDURE delta.`SP_CP_PRO_PUBLICACION_CONSULTA_REFERENCIA`(OUT codErr INTEGER)
BEGIN

DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;
SET codErr=0;
  IF EXISTS(SELECT * FROM PUBLICACION_LIST_REFERENCIA) THEN 
    SELECT RETIPO FROM PUBLICACION_LIST_REFERENCIA ORDER BY REID ASC;
  ELSE
    SET codErr=98;
  END IF;    
  
END;

