CALL SP_CAT_CSU_CON2(@codErr);
SELECT @codErr;

DROP PROCEDURE IF EXISTS bodyflex.SP_CAT_CSU_CON2;
CREATE PROCEDURE bodyflex.`SP_CAT_CSU_CON2`(OUT codErr INTEGER)
BEGIN
  DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;
  SET codErr=0;
  IF EXISTS(SELECT PARVAL FROM PARAMETROS WHERE PARNOM='CONTACTO')THEN
    SET @VAL1=(SELECT PARVAL FROM PARAMETROS WHERE PARNOM='CONTACTO');
    SET @VAL2=(SELECT PARVAL FROM PARAMETROS WHERE PARNOM='MAIL');
    SELECT @VAL1,@VAL2; 
  ELSE
    SET codErr=98;
  END IF;  
END



-- SELECT * FROM PARAMETROS
