
-- select * from servicio

-- CALL SP_ADMIN_SERVICIO_PROFE_CONSULTA();

DROP PROCEDURE IF EXISTS bodyflex.SP_CP_ADM_SERVICIO_PROFE_CONSULTA;
CREATE PROCEDURE bodyflex.`SP_CP_ADM_SERVICIO_PROFE_CONSULTA`(OUT codErr INTEGER)
BEGIN
  
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';
SET codErr=0;
  IF EXISTS(SELECT * FROM SERVICIO) THEN
  
    SET @CANT=(SELECT COUNT(*) FROM SERVICIO);
    
    SELECT SEID
      , SENOM
      , SEDESCOR
      , SEDESLAR
      , SEIMGAWE
      , SEIMGSER
      , SEIDFLI
      , @CANT
      FROM SERVICIO
      ORDER BY SEID DESC;
  
  ELSE
  
    SET codErr=98;  
  
  END IF;    
END;
