CALL SP_CAT_SLD_CSU_T4(@codErr);
SELECT @codErr;


DROP PROCEDURE IF EXISTS bodyflex.SP_CAT_SLD_CSU_T4;
CREATE PROCEDURE bodyflex.`SP_CAT_SLD_CSU_T4`(OUT codErr INTEGER)
BEGIN
  
  -- DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;
  SET codErr=0;
    
  IF EXISTS(SELECT PARVAL FROM PARAMETROS WHERE PARNOM='DRIVE')THEN  
    SET @URL_DRIVE=(SELECT PARVAL FROM PARAMETROS WHERE PARNOM='DRIVE');

    -- verificamos si el producto asociado a este slider existe
    SET @ID1=(SELECT CS4PO1 FROM CATALOGO_SLIDER4);
    IF EXISTS(SELECT * FROM PRODUCTO WHERE PROID=@ID1) THEN
      SET @URL_PRODUCTO1=(SELECT CS4URL1 FROM CATALOGO_SLIDER4);
      SET @CS4PO1=(SELECT CS4PO1 FROM CATALOGO_SLIDER4);
    ELSE
      SET @URL_PRODUCTO1=(SELECT PARVAL FROM PARAMETROS WHERE PARNOM='CATALOGO'); -- LA IDEA ES QUE CUANDO EL PRODUCTO NO EXISTA SE REDIRECCIONE AL CATALOGO
      SET @CS4PO1=0;
    END IF;
   
    SET @ID2=(SELECT CS4PO2 FROM CATALOGO_SLIDER4);
    IF EXISTS(SELECT * FROM PRODUCTO WHERE PROID=@ID2) THEN
      SET @URL_PRODUCTO2=(SELECT CS4URL2 FROM CATALOGO_SLIDER4);
      SET @CS4PO2=(SELECT CS4PO2 FROM CATALOGO_SLIDER4);
    ELSE
      SET @URL_PRODUCTO2=(SELECT PARVAL FROM PARAMETROS WHERE PARNOM='CATALOGO'); -- LA IDEA ES QUE CUANDO EL PRODUCTO NO EXISTA SE REDIRECCIONE AL CATALOGO
      SET @CS4PO2=0;
    END IF;
    
    SET @ID3=(SELECT CS4PO3 FROM CATALOGO_SLIDER4);
    IF EXISTS(SELECT * FROM PRODUCTO WHERE PROID=@ID3) THEN
      SET @URL_PRODUCTO3=(SELECT CS4URL3 FROM CATALOGO_SLIDER4);
      SET @CS4PO3=(SELECT CS4PO3 FROM CATALOGO_SLIDER4);
    ELSE
      SET @URL_PRODUCTO3=(SELECT PARVAL FROM PARAMETROS WHERE PARNOM='CATALOGO'); -- LA IDEA ES QUE CUANDO EL PRODUCTO NO EXISTA SE REDIRECCIONE AL CATALOGO
      SET @CS4PO3=0;
    END IF;
    
    SET @ID4=(SELECT CS4PO4 FROM CATALOGO_SLIDER4);
    IF EXISTS(SELECT * FROM PRODUCTO WHERE PROID=@ID4) THEN
      SET @URL_PRODUCTO4=(SELECT CS4URL4 FROM CATALOGO_SLIDER4);
      SET @CS4PO4=(SELECT CS4PO4 FROM CATALOGO_SLIDER4);
    ELSE
      SET @URL_PRODUCTO4=(SELECT PARVAL FROM PARAMETROS WHERE PARNOM='CATALOGO'); -- LA IDEA ES QUE CUANDO EL PRODUCTO NO EXISTA SE REDIRECCIONE AL CATALOGO
      SET @CS4PO4=0;
    END IF;

    IF EXISTS(SELECT * FROM CATALOGO_SLIDER4)THEN
      SELECT CS4ID
      , CS4GD1
      , CS4GD2
      , CS4GD3
      , CS4GD4
      , CS4B1
      , CS4B2
      , @URL_PRODUCTO1
      , @URL_PRODUCTO2
      , @URL_PRODUCTO3
      , @URL_PRODUCTO4
      , @URL_DRIVE
      , @CS4PO1
      , @CS4PO2
      , @CS4PO3
      , @CS4PO4
      FROM CATALOGO_SLIDER4 ORDER BY CS4ID ASC; 
    ELSE
      SET codErr=98;
    END IF;
  ELSE
    SET codErr=97;
  END IF;
END




