-- CALL SP_CP_ADM_CSU_PRO_ADD_COL(37, @codErr);
-- SELECT @codErr;

-- SELECT * FROM PRODUCTO
-- SELECT * FROM PARAMETROS

DROP PROCEDURE IF EXISTS bodyflex.SP_CP_ADM_CSU_PRO_ADD_COL;
CREATE PROCEDURE bodyflex.`SP_CP_ADM_CSU_PRO_ADD_COL`(
                                                      IN id VARCHAR(10)      
                                                      , OUT codErr INTEGER
                                                      )
BEGIN
  -- CONSULTA IMAGENES COLECCION PARA PORTADA DE CATALOGO
  -- DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;
  
  SET @GD=(SELECT PARVAL FROM PARAMETROS WHERE PARID=1);
  
  IF EXISTS(
      SELECT * 
      FROM PRODUCTO P
      WHERE P.PROID=id
    ) THEN
  
    SELECT P.PRONO
    , (SELECT PCP1_ID FROM PRODUCTO_CATEGORIA1 WHERE PCP1_ID=P.PCP1_ID) AS ID_CAT1
    , (SELECT PCP1_NOM FROM PRODUCTO_CATEGORIA1 WHERE PCP1_ID=P.PCP1_ID) AS NOM_CAT1
    , IFNULL((SELECT PCP2_ID FROM PRODUCTO_CATEGORIA2 WHERE PCP2_ID=P.PCP2_ID),0) AS ID_CAT2
    , IFNULL((SELECT PCP2_NOM FROM PRODUCTO_CATEGORIA2 WHERE PCP2_ID=P.PCP2_ID),'') AS NOM_CAT2
    , IFNULL((SELECT PCP3_ID FROM PRODUCTO_CATEGORIA3 WHERE PCP3_ID=P.PCP3_ID),0) AS ID_CAT3
    , IFNULL((SELECT PCP3_NOM FROM PRODUCTO_CATEGORIA3 WHERE PCP3_ID=P.PCP3_ID),'') AS NOM_CAT3
    , (SELECT PCO_DRI FROM PRODUCTO_CONTENIDO WHERE PROID=P.PROID AND PCO_PRI=1) AS URL
    FROM PRODUCTO P
    WHERE P.PROID=id;
    
  ELSE
    SET codErr=98;  
  END IF;
 
END

-- SELECT * FROM COLECCION C, COLECCION_PRODUCTO CP WHERE C.COID=CP.COID;
-- SELECT * FROM COLECCION
-- SELECT * FROM COLECCION_PRODUCTO

