
-- CALL SP_CP_ADM_PRODUCTO_CONSULTA_CONTENIDO(150,@corErr);

-- CALL SP_CP_ADM_PRODUCTO_CONSULTA_CONTENIDO(25,@corErr);
-- SELECT @corErr AS corErr;

-- CALL SP_CP_ADM_PRODUCTO_CONSULTA_CONTENIDO(23,@corErr);
-- SELECT @corErr AS corErr;

-- SELECT * FROM PRODUCTO_CONTENIDO

-- CALL SP_CP_ADM_PRODUCTO_CONSULTA_CONTENIDO(25);

DROP PROCEDURE IF EXISTS bodyflex.SP_CP_ADM_PRODUCTO_CONSULTA_CONTENIDO;
CREATE PROCEDURE bodyflex.`SP_CP_ADM_PRODUCTO_CONSULTA_CONTENIDO`(
  IN idPro VARCHAR(20)
  , OUT codErr INTEGER
)
BEGIN

-- DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;

SET codErr=0;

  IF EXISTS(SELECT * FROM PRODUCTO_CONTENIDO WHERE proID=idPro) THEN    
    SELECT PC.pco_id
    , PC.pco_tip
    , PC.pco_dri
    FROM PRODUCTO_CONTENIDO PC, PRODUCTO PP
    WHERE PP.PROID=PC.PROID AND (PP.PROET='ALTA' OR PP.PROET='INGRESADO') AND PC.proID=idPro
    ORDER BY PC.pco_id DESC;
  ELSE
    SET codErr=98;
  END IF;

END;
