
-- CALL SP_CP_ADM_MOD_EST_POS_DET('12','NUEVO','wwwwwwwwwwwww','2222222','wwwwwwwwwwwww','2','0','0','wwwwwwwwwwwww','9386703');


-- SELECT * FROM POSTULACION;

DROP PROCEDURE IF EXISTS bodyflex.SP_CP_ADM_MOD_EST_POS_DET;
CREATE PROCEDURE bodyflex.`SP_CP_ADM_MOD_EST_POS_DET`(IN id VARCHAR(20), OUT codErr INTEGER)
BEGIN

DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;

SET codErr=0;

    IF EXISTS(SELECT * FROM POSTULACION WHERE POSID=id) THEN
      UPDATE POSTULACION 
      SET POSEST = 3 -- DETENIDA
      WHERE POSID=id;
      SELECT 1;
    ELSE
      SET codErr=98;
    END IF;
      
END;
