-- CALL SP_CP_ADM_ELIMINA_PRODUCTO(7, @codErr);
-- SELECT @codErr;

-- SELECT * FROM PRODUCTO;

DROP PROCEDURE IF EXISTS bodyflex.SP_CP_ADM_ELIMINA_PRODUCTO;
CREATE PROCEDURE bodyflex.`SP_CP_ADM_ELIMINA_PRODUCTO`(
                                        IN id VARCHAR(20)
                                        , OUT codErr INTEGER
                                        )
BEGIN

-- DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;
SET codErr=0;

  DELETE FROM PRODUCTO_PROFESIONAL WHERE proID=id;    
  DELETE FROM PRODUCTO_CONTENIDO WHERE proID=id;    
  DELETE FROM PRODUCTO_VOTACION WHERE proID=id;  
  DELETE FROM PRODUCTO_PUNTUACION WHERE proID=id;  
  DELETE FROM PRODUCTO_DENUNCIA WHERE proID=id;  
  DELETE FROM PRODUCTO_VISITAS WHERE proID=id;
  DELETE FROM PRODUCTO_MEDIDA WHERE proID=id;
  DELETE FROM COLECCION_PRODUCTO WHERE proID=id;
  DELETE FROM PRODUCTO_COLOR WHERE proID=id;  
  DELETE FROM PRODUCTO_COMENTARIO_PROFESIONAL WHERE proID=id;  
  DELETE FROM PRODUCTO WHERE proID=id;    
  SELECT 1;

END;
