-- CALL SP_CV_PRO_GET_BIO('13661574', @codErr);
-- SELECT @codErr;

-- SELECT * FROM PROFESIONAL;
-- SELECT * FROM PORTAFOLIO;
-- SELECT * FROM PARAMETROS;
-- SELECT * FROM PROFESIONAL_PERFIL

DROP PROCEDURE IF EXISTS bodyflex.SP_CV_PRO_GET_BIO;
CREATE PROCEDURE bodyflex.`SP_CV_PRO_GET_BIO`(
                                            IN rut VARCHAR(20)
                                            , OUT codErr INTEGER
                                          )
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;
SET codErr=0;

  IF EXISTS(SELECT * FROM ESTUDIOS WHERE PRUT = rut) THEN
    
    SET @NOM = (SELECT CONCAT(PNOM,' ',PAPE) FROM PROFESIONAL WHERE PRUT=rut);
    SET @TIP = (SELECT PTIPO2 FROM PROFESIONAL WHERE PRUT=rut);
    SET @ESP = (SELECT PERESP FROM PROFESIONAL_PERFIL WHERE PRUT=rut);
    SET @PRE = (SELECT PTXTOPRE FROM PROFESIONAL WHERE PRUT=rut);
    SET @PAR = (SELECT PARVAL FROM PARAMETROS WHERE PARNOM='DRIVE');
    SET @REG = (SELECT COUNT(*) FROM PORTAFOLIO WHERE PRUT=rut);
      
    SELECT @NOM AS 'NOM'
    , @TIP AS 'TIP'
    , @ESP AS 'ESP'
    , @PRE AS 'PRE'
    , @PAR AS 'DRI'
    , PONOMCAP
    , POIDFLI
    , @REG
    FROM PORTAFOLIO
    WHERE PRUT=rut;
    
  ELSE
    SET codErr=98;    
  END IF;
  
END




