
-- SELECT * FROM PARAMETROS;

CALL SP_CP_ADM_CSU_PARAMETROS(@codErr);
SELECT @codErr AS corErr;

DROP PROCEDURE IF EXISTS bodyflex.SP_CP_ADM_CSU_PARAMETROS ;
CREATE PROCEDURE bodyflex.`SP_CP_ADM_CSU_PARAMETROS`(OUT codErr INTEGER)
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;

  SET codErr=0;
  SET @existe=0;
  IF EXISTS(SELECT * FROM PARAMETROS WHERE PARNOM='IVA')THEN
    SET @IVA=(SELECT PARVAL FROM PARAMETROS WHERE PARNOM='IVA');
  ELSE
    SET @existe=1;
  END IF;
  IF EXISTS(SELECT * FROM PARAMETROS WHERE PARNOM='TRANSBANK')THEN
    SET @TRA=(SELECT PARVAL FROM PARAMETROS WHERE PARNOM='TRANSBANK');
  ELSE
    SET @existe=1;  
  END IF;  
  IF @existe=1 THEN
    SET codErr=98;
  ELSE
    SELECT @IVA AS IVA, @TRA AS TRA;
  END IF;
  
END




