-- SELECT * FROM PRODUCTO P, PRODUCTO_CONTENIDO PC WHERE P.PROID = PC.PROID AND P.PROID=8;
-- SELECT * FROM PRODUCTO_CONTENIDO PC WHERE PC.PROID =8;
-- SELECT * FROM PARAMETROS

CALL SP_CAT_CSU_PRO_REL(13, @codErr);
SELECT @codErr;

CALL SP_CAT_CSU_PRO_REL(5, @codErr);
SELECT @codErr;

DROP PROCEDURE IF EXISTS bodyflex.SP_CAT_CSU_PRO_REL;
CREATE PROCEDURE bodyflex.`SP_CAT_CSU_PRO_REL`(
                                                IN codPro VARCHAR(10)
                                                , OUT codErr INTEGER
                                              )
BEGIN
  
  -- DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;
  SET codErr=0;
  SET @URL_DRIVE=(SELECT PARVAL FROM PARAMETROS WHERE PARNOM='DRIVE');
  SET @PRODUCTO=(SELECT PARVAL FROM PARAMETROS WHERE PARNOM='PRODUCTO');
  SET @SW=0;
  SET @numero1=0;  
  SET @numero2=0;  
  
  CREATE TEMPORARY TABLE tmp_pro_col (
    PROID VARCHAR(10) NOT NULL
    , SCOLORES VARCHAR(100) NOT NULL
  );

  SET @cat1=(SELECT PCP1_ID FROM PRODUCTO WHERE PROID=codPro);
  SET @cat2=(SELECT PCP2_ID FROM PRODUCTO WHERE PROID=codPro);
  SET @cat3=(SELECT PCP3_ID FROM PRODUCTO WHERE PROID=codPro);

  -- 1° TABLA TEMPORAL
  CREATE TEMPORARY TABLE TMP_proRel
  SELECT @numero1:=@numero1+1 AS POS
  , P.PROID
  , P.PRONO
  , CONCAT('$',REPLACE(FORMAT(P.PROPVP,0),',','.')) AS PROPVP
  , (SELECT PCO_DRI FROM PRODUCTO_CONTENIDO WHERE PROID=P.PROID AND PCO_PRI=1 ORDER BY PCO_ID DESC LIMIT 1) AS IMAGEN1
  , (SELECT PCO_DRI FROM PRODUCTO_CONTENIDO WHERE PROID=P.PROID AND PCO_PRI<>1 ORDER BY PCO_ID DESC LIMIT 1) AS IMAGEN2
  , (SELECT COUNT(*) FROM PRODUCTO_COLOR WHERE PROID=P.PROID) AS NCOLORES
  , (SELECT COUNT(*) FROM PRODUCTO_CONTENIDO WHERE PROID=P.PROID) AS IMAGENES
  , @URL_DRIVE AS URL_DRIVE
  , @PRODUCTO AS PRODUCTO
  FROM PRODUCTO P
  WHERE P.PROID<>codPro
  AND (
        (P.PCP1_ID=@cat1 AND P.PCP2_ID=@cat2 AND P.PCP3_ID=@cat3) OR
        (P.PCP1_ID=@cat1 AND P.PCP2_ID=@cat2) OR
        (P.PCP1_ID=@cat1) OR (P.PCP1_ID<>@cat1)
      ) 
  AND P.proPE=1
  ORDER BY P.PROID 
  ASC LIMIT 4;
   
  -- 2° RECORREMOS TABLA TEMPORAL
  SET @REGISTROS=(SELECT COUNT(*) FROM TMP_proRel);
  SET @CONT=1;   
  WHILE @CONT<=4 AND @CONT<=@REGISTROS DO
  
    -- 1° Obtenemos ID & N°
    SET @ID=(SELECT PROID FROM TMP_proRel WHERE POS=@CONT);
    SET @NC=(SELECT COUNT(*) FROM PRODUCTO_COLOR WHERE PROID=@ID); 
        
    -- 2° Creamos tbl_tmp
    CREATE TEMPORARY TABLE TMP_proColores
    SELECT @numero2:=@numero2+1 AS POS, PCOB FROM PRODUCTO_COLOR WHERE PROID=@ID;
    
      -- 3° Obtenemos Colores
      SET @SC='';
      SET @TC='';
      SET @CC=1;
      
      WHILE @CC<=@NC DO
        SET @SC=CONCAT((SELECT PCOB FROM TMP_proColores WHERE POS=@CC),'|');
        SET @TC=CONCAT(@TC,@SC);
        SET @SC='';
        SET @CC=@CC+1;
      END WHILE;
    
    INSERT INTO tmp_pro_col(PROID, SCOLORES) VALUES (@ID, @TC);
    DROP TABLE TMP_proColores;
      
    SET @TC='';
    SET @ID='';
    SET @NC='';
    SET @numero2=0;  
    SET @CONT=@CONT+1;
    
  END WHILE;
  
  -- MOSTRAMOS RESULTADOS
  SELECT t1.PROID
  , t1.PRONO
  , t1.PROPVP
  , t1.IMAGEN1
  , t1.IMAGEN2
  , t1.NCOLORES
  , t1.IMAGENES
  , t1.URL_DRIVE
  , t2.SCOLORES
  , t1.PRODUCTO
  FROM TMP_proRel t1, tmp_pro_col t2
  WHERE t1.PROID=t2.PROID
  ORDER BY t1.PROID ASC;
  
  DROP TABLE TMP_proRel;
  DROP TABLE tmp_pro_col;
    
END


-- SELECT * FROM PRODUCTO_COLOR

