CALL SP_CAT_CSU_COL_POR(@codErr);
SELECT @codErr;

-- SELECT * FROM COLECCION
-- SELECT * FROM PARAMETROS

DROP PROCEDURE IF EXISTS bodyflex.SP_CAT_CSU_COL_POR;
CREATE PROCEDURE bodyflex.`SP_CAT_CSU_COL_POR`(OUT codErr INTEGER)
BEGIN
  -- CONSULTA IMAGENES COLECCION PARA PORTADA DE CATALOGO
  -- DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;
  
  SET @GD=(SELECT PARVAL FROM PARAMETROS WHERE PARID=1);
  
  IF EXISTS(
      SELECT * 
      FROM COLECCION C, COLECCION_PRODUCTO CP 
      WHERE C.COID=CP.COID
    ) THEN
  
    /*
    SELECT REPLACE(@GD, 'FILEID', coGD3) AS URL
    FROM COLECCION C, COLECCION_PRODUCTO CP
    WHERE C.COID=CP.COID
    ORDER BY C.COID DESC
    LIMIT 4;
    */
    
    SELECT C.COID
    , REPLACE(@GD, 'FILEID', coGD3) AS URL
    FROM COLECCION C
    LEFT JOIN COLECCION_PRODUCTO CP
    ON C.COID=CP.COID 
    GROUP BY URL
    ORDER BY RAND()LIMIT 4; 
    
  ELSE
    SET codErr=98;  
  END IF;
 
END

  



-- SELECT * FROM COLECCION C, COLECCION_PRODUCTO CP WHERE C.COID=CP.COID;
-- SELECT * FROM COLECCION
-- SELECT * FROM COLECCION_PRODUCTO

