

-- CALL SP_CP_ADM_PUBLICACION_ELIMINA('74', @codErr);
-- SELECT @codErr;
   
-- SELECT * FROM PUBLICACION;

DROP PROCEDURE IF EXISTS bodyflex.SP_CP_ADM_PUBLICACION_ELIMINA;
CREATE PROCEDURE bodyflex.`SP_CP_ADM_PUBLICACION_ELIMINA`(
                                                        IN id VARCHAR(20)
                                                        , OUT codErr INTEGER
                                                    )
BEGIN
  
  DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;
  SET codErr=0;
    
    DELETE FROM PUBLICACION_COMENTARIO WHERE PUID=id;
    DELETE FROM PUBLICACION_VOTACION WHERE PUID=id;
    DELETE FROM PUBLICACION_DENUNCIA WHERE PUID=id;
    DELETE FROM PUBLICACION_VISITAS WHERE PUID=id;
    DELETE FROM PUBLICACION_CONTENIDO WHERE PUID=id;
    DELETE FROM PUBLICACION_ETIQUETA WHERE PUID=id;
    DELETE FROM PUBLICACION_REFERENCIA WHERE PUID=id;
    DELETE FROM PUBLICACION_PROFESIONAL WHERE PUID=id;
    DELETE FROM PUBLICACION_INTERNO WHERE PUID=id;
    DELETE FROM PUBLICACION_COMPLEMENTADOR WHERE PUID=id;
    SELECT 1;
           
END;
