CALL SP_CAT_SLD_CSU_T2(@codErr);
SELECT @codErr;

-- select * from CATALOGO_SLIDER2
-- select * from COLECCION

DROP PROCEDURE IF EXISTS bodyflex.SP_CAT_SLD_CSU_T2;
CREATE PROCEDURE bodyflex.`SP_CAT_SLD_CSU_T2`(OUT codErr INTEGER)
BEGIN
  
  -- DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;
  SET codErr=0;
  
  IF EXISTS(SELECT PARVAL FROM PARAMETROS WHERE PARNOM='DRIVE') THEN
  
    SET @URL_DRIVE=(SELECT PARVAL FROM PARAMETROS WHERE PARNOM='DRIVE');
    
    -- verificamos si el producto asociado a este slider existe
    SET @ID=(SELECT CS2PO FROM CATALOGO_SLIDER2);
    IF EXISTS(SELECT * FROM PRODUCTO WHERE PROID=@ID) THEN
      SET @URL_PRODUCTO=(SELECT CS2URL2 FROM CATALOGO_SLIDER2);
      SET @CS2PO=(SELECT CS2PO FROM CATALOGO_SLIDER2);
    ELSE
      SET @URL_PRODUCTO=(SELECT PARVAL FROM PARAMETROS WHERE PARNOM='CATALOGO'); -- LA IDEA ES QUE CUANDO EL PRODUCTO NO EXISTA SE REDIRECCIONE AL CATALOGO
      SET @CS2PO=0;
    END IF;
    
    -- verificamos si la colección asociado a este slider existe
    SET @ID=(SELECT CS2CO FROM CATALOGO_SLIDER2);
    IF EXISTS(SELECT * FROM COLECCION WHERE COID=@ID) THEN
      SET @CS2CO=(SELECT CS2CO FROM CATALOGO_SLIDER2);
    ELSE
      SET @CS2CO=0;
    END IF;
    
    IF EXISTS(SELECT * FROM CATALOGO_SLIDER2)THEN
      SELECT S2.CS2ID
      , S2.CS2TI
      , S2.CS2DE
      , CONCAT('$',REPLACE(FORMAT(IFNULL((SELECT proPvp FROM PRODUCTO WHERE PROID=S2.CS2PO),0),0),',','.')) AS CS2PR 
      , S2.CS2GD1
      , S2.CS2GD2
      , S2.CS2URL1 AS CS2URL1-- URL A LA CATEGORIA/COLECCIÓN
      , @URL_PRODUCTO AS CS2URL2 -- URL AL PRODUCTO
      , @CS2CO
      , @CS2PO
      , @URL_DRIVE AS DRIVE
      FROM CATALOGO_SLIDER2 S2
      ORDER BY S2.CS2ID ASC; 
    ELSE
      SET codErr=98;
    END IF;
  ELSE
    SET codErr=97;
  END IF;
END




