
-- SELECT * FROM REGION;

-- CALL SP_CP_ADM_DIR_CSU_REG(@codErr);
-- SELECT @codErr;

DROP PROCEDURE IF EXISTS bodyflex.SP_CP_ADM_DIR_CSU_REG;
CREATE PROCEDURE bodyflex.`SP_CP_ADM_DIR_CSU_REG`(OUT codErr INTEGER)
BEGIN

DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;
SET codErr=0;
  IF EXISTS(SELECT * FROM REGION) THEN
      SELECT rNom
      FROM REGION
      ORDER BY rNom ASC;
  ELSE
    SET codErr=98;
  END IF;

END




