

-- CALL SP_CP_PRO_ELI_DIR_PRO('11',@codErr);
-- SELECT @codErr;
   
-- SELECT * FROM PROFESIONAL;
-- SELECT * FROM PROFESIONAL_DIRECCION
-- SELECT * FROM DIRECCION


DROP PROCEDURE IF EXISTS bodyflex.SP_CP_PRO_ELI_DIR_PRO;
CREATE PROCEDURE bodyflex.`SP_CP_PRO_ELI_DIR_PRO`(
                                                IN vId VARCHAR(20)
                                                , OUT codErr INTEGER
                                                )
BEGIN
  
  -- DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;
  SET codErr=0;
  SET @PRUT=(SELECT PRUT FROM PROFESIONAL_DIRECCION WHERE DCOD=vId);
  
  DELETE FROM PROFESIONAL_DIRECCION WHERE DCOD=vId;    
  DELETE FROM COORDENADAS WHERE DCOD=vId;
  DELETE FROM DIRECCION WHERE DCOD=vId;
  -- CAMBIAMOS ESTADO SI NO POSEE DIRECCIONES
  IF NOT EXISTS(SELECT * FROM PROFESIONAL_DIRECCION WHERE PRUT=@PRUT)THEN
    UPDATE PROFESIONAL SET PEST=1 WHERE PRUT=@PRUT;
  END IF;
  SELECT 1;
          
END;
