DROP PROCEDURE IF EXISTS bodyflex.SP_CP_ADM_CSU_CAT1_CMB;
CREATE PROCEDURE bodyflex.`SP_CP_ADM_CSU_CAT1_CMB`(OUT codErr INTEGER)
BEGIN
 
  DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;    
  SET codErr=0;
    IF EXISTS(SELECT * FROM PRODUCTO_CATEGORIA1)THEN
      SELECT PCP1_ID
      , PCP1_NOM
      FROM PRODUCTO_CATEGORIA1
      ORDER BY PCP1_NOM ASC;
    ELSE
      SET codErr=98;
    END IF;  
  
END;
