
-- select * from servicio
-- select * from profesional

-- CALL SP_CP_PRO_SERVICIO_PROFESIONAL_OBTIENE_TODOS(9386703);

DROP PROCEDURE IF EXISTS bodyflex.SP_CP_PRO_SERVICIO_PROFESIONAL_OBTIENE_TODOS;
CREATE PROCEDURE bodyflex.`SP_CP_PRO_SERVICIO_PROFESIONAL_OBTIENE_TODOS`(
                                                                  IN rut VARCHAR(10)
                                                                  , OUT codErr INTEGER
                                                                )
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;  
  SET codErr=0;
  IF EXISTS(SELECT * FROM PROFESIONAL_SERVICIO WHERE PRUT=rut) THEN
    SET @CANT=(SELECT COUNT(*) FROM PROFESIONAL_SERVICIO);
    SELECT PS.PSID AS PSID 
      , (SELECT S.SEID FROM SERVICIO S WHERE S.SEID=PS.SEID) AS SEID
      , (SELECT S.SENOM FROM SERVICIO S WHERE S.SEID=PS.SEID) AS SERNOM
      , (SELECT S.SEDESCOR FROM SERVICIO S WHERE S.SEID=PS.SEID) AS SEDESCOR
      , (SELECT S.SEDESLAR FROM SERVICIO S WHERE S.SEID=PS.SEID) AS SEDESLAR
      , @CANT
      FROM PROFESIONAL_SERVICIO PS
      WHERE PRUT=rut
      ORDER BY PS.PSID;
  ELSE
    SET codErr=98;    
  END IF;    
END;
