CALL SP_CP_ADM_CONSULTA_CATEGORIAS_PRODUCTOS(1,0,@codErr);
SELECT @codErr;

-- CALL SP_CP_ADM_CONSULTA_CATEGORIAS_PRODUCTOS(2,1,@codErr);
-- CALL SP_CP_ADM_CONSULTA_CATEGORIAS_PRODUCTOS(2,2,@codErr);
-- CALL SP_CP_ADM_CONSULTA_CATEGORIAS_PRODUCTOS(2,3,@codErr);
-- CALL SP_CP_ADM_CONSULTA_CATEGORIAS_PRODUCTOS(3,4,@codErr);
-- &#209;
-- SELECT * FROM PRODUCTO_CATEGORIA1
-- SELECT * FROM PRODUCTO_CATEGORIA2
-- SELECT * FROM PRODUCTO_CATEGORIA3

DROP PROCEDURE IF EXISTS bodyflex.SP_CP_ADM_CONSULTA_CATEGORIAS_PRODUCTOS;
CREATE PROCEDURE bodyflex.`SP_CP_ADM_CONSULTA_CATEGORIAS_PRODUCTOS`(
                                                    IN nivelCat INTEGER
                                                    , IN nivelCod INTEGER
                                                    , OUT codErr INTEGER
                                                 )
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;

SET codErr=0;

  CASE nivelCat
    WHEN 1 THEN
      IF EXISTS(SELECT * FROM PRODUCTO_CATEGORIA1) THEN
        SELECT PCP1_ID, PCP1_NOM FROM PRODUCTO_CATEGORIA1 ORDER BY PCP1_NOM ASC;
      ELSE
        SET codErr=98;
      END IF;
    WHEN 2 THEN
      IF EXISTS(SELECT * FROM PRODUCTO_CATEGORIA2 WHERE PCP1_ID=nivelCod) THEN
        SELECT PCP2_ID, PCP2_NOM FROM PRODUCTO_CATEGORIA2 WHERE PCP1_ID=nivelCod ORDER BY PCP2_NOM ASC;
      ELSE
        SET codErr=98;
      END IF;
    WHEN 3 THEN
      IF EXISTS(SELECT * FROM PRODUCTO_CATEGORIA3 WHERE PCP2_ID=nivelCod) THEN
        SELECT PCP3_ID, PCP3_NOM FROM PRODUCTO_CATEGORIA3 WHERE PCP2_ID=nivelCod ORDER BY PCP3_NOM ASC;
      ELSE
        SET codErr=98;
      END IF;
  END CASE;
  
END




