CALL SP_CAT_SLD_CSU_T5(@codErr);
SELECT @codErr;

DROP PROCEDURE IF EXISTS bodyflex.SP_CAT_SLD_CSU_T5;
CREATE PROCEDURE bodyflex.`SP_CAT_SLD_CSU_T5`(OUT codErr INTEGER)
BEGIN
  
  DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;
  SET codErr=0;
  
  IF EXISTS(SELECT PARVAL FROM PARAMETROS WHERE PARNOM='DRIVE')THEN
    SET @URL_DRIVE=(SELECT PARVAL FROM PARAMETROS WHERE PARNOM='DRIVE');
    IF EXISTS(SELECT * FROM CATALOGO_SLIDER5)THEN
      SELECT CS5ID
      , CS5TI
      , CS5B1
      , CS5DE
      , CS5GD
      , CS5URL
      , @URL_DRIVE 
      , CS5CO
      FROM CATALOGO_SLIDER5 ORDER BY CS5ID ASC;
    ELSE
      SET codErr=98;
    END IF;  
  ELSE
    SET codErr=97;
  END IF;
END




