-- select * from PRODUCTO_CATEGORIA2


CALL SP_CP_ADM_CSU_CAT3_CMB(1 ,@codErr);
SELECT @codErr;

DROP PROCEDURE IF EXISTS bodyflex.SP_CP_ADM_CSU_CAT3_CMB;
CREATE PROCEDURE bodyflex.`SP_CP_ADM_CSU_CAT3_CMB`(IN cat2 INTEGER, OUT codErr INTEGER)
BEGIN
 
  DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;    
  SET codErr=0;
    IF EXISTS(SELECT * FROM PRODUCTO_CATEGORIA3 WHERE PCP2_ID=cat2)THEN
      SELECT PCP3_ID
      , PCP3_NOM
      FROM PRODUCTO_CATEGORIA3
      WHERE PCP2_ID=cat2
      ORDER BY PCP3_NOM ASC;
    ELSE
      SET codErr=98;
    END IF;  
  
END;
