
-- CALL SP_CP_ADM_CSU_RAN_PRE(@codErr);
-- SELECT @codErr;

DROP PROCEDURE IF EXISTS bodyflex.SP_CP_ADM_CSU_RAN_PRE;
CREATE PROCEDURE bodyflex.`SP_CP_ADM_CSU_RAN_PRE`( OUT codErr INTEGER )
BEGIN
 
  -- DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;    
  SET codErr=0;
  IF EXISTS(SELECT * FROM CATALOGO_RANGO_PRECIO)THEN
    SELECT RP.RAN_ID, RP.RAN_INF, RP.RAN_SUP FROM CATALOGO_RANGO_PRECIO RP ORDER BY RP.RAN_ID ASC; 
  ELSE
    SET codErr=98;
  END IF;
END;

-- SELECT * FROM CATALOGO_RANGO_PRECIO
