
-- CALL SP_CP_PRO_PUBLICACION_INGRESA_CATEGORIA_ETIQUETA('13661574','PEO');
-- CALL SP_CP_PRO_PUBLICACION_INGRESA_CATEGORIA_ETIQUETA('13661574','FITNESS');
-- CALL SP_CP_PRO_PUBLICACION_INGRESA_CATEGORIA_ETIQUETA('13661574','fitness');
-- CALL SP_CP_PRO_PUBLICACION_INGRESA_CATEGORIA_ETIQUETA('13661574','OTRA');
   
-- SELECT * FROM PROFESIONAL
-- SELECT * FROM PUBLICACION_CATEGORIA_ETIQUETA
-- SELECT * FROM PUBLICACION_LIST_ETIQUETAS

DROP PROCEDURE IF EXISTS delta.SP_CP_PRO_PUBLICACION_INGRESA_CATEGORIA_ETIQUETA;
CREATE PROCEDURE delta.`SP_CP_PRO_PUBLICACION_INGRESA_CATEGORIA_ETIQUETA`( 
                                                                IN rut VARCHAR(20)
                                                              , IN cat VARCHAR(50)
                                                              , OUT codErr INTEGER
                                                            )
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;
SET codErr=0;
    -- 1 DETERMINAR EXISTENCIA DEL REGISTRO
    IF NOT EXISTS(SELECT CATETINOM FROM PUBLICACION_CATEGORIA_ETIQUETA WHERE CATETINOM=upper(cat)) THEN
      INSERT INTO PUBLICACION_CATEGORIA_ETIQUETA(
        CATRUT
      , CATETINOM
      )VALUES(
        rut
        , UPPER(cat)
      );
      SELECT 1;
    ELSE -- EL REGISTRO EXISTE  
      SET codErr=98;     
    END IF;
END;
