

CALL SP_CP_PRO_PUBLICACION_VALIDA_ELEMENTOS(12, @codErr);
SELECT @codErr;

DROP PROCEDURE IF EXISTS delta.SP_CP_PRO_PUBLICACION_VALIDA_ELEMENTOS;
CREATE PROCEDURE delta.`SP_CP_PRO_PUBLICACION_VALIDA_ELEMENTOS`(
                                                              IN idPu VARCHAR(20)
                                                              , OUT codErr INTEGER
                                                            )
BEGIN

DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;
SET codErr=0;

  -- 1 -- POSE ESOLO ETIQUETAS
  -- 2 -- POSEE SOLO REFERENCIAS
  -- 3 -- POSEE SOLO IMAGENES
  -- 4 -- POSEE ETIQUETAS Y REFERENCIAS
  -- 5 -- POSEE ETIQUETAS E IMAGENES
  -- 6 -- POSEE REFERENCIAS E IMAGENES
  -- 7 -- POSEE REFERENCIAS, ETIQUETAS E IMAGENES
  -- 8 -- NO POEE NADA

  SET @REF=IF(EXISTS(SELECT * FROM PUBLICACION_REFERENCIA WHERE PUID=idPu), 1, 0);
  SET @ETI=IF(EXISTS(SELECT * FROM PUBLICACION_ETIQUETA WHERE PUID=idPu), 1, 0);
  SET @IMG=IF(EXISTS(SELECT * FROM PUBLICACION_CONTENIDO WHERE PUID=idPu), 1, 0);

  -- 1° DETERMINAMOS GRUPO
  CASE
    WHEN (@ETI=0 AND @REF=0 AND @IMG=0) THEN SELECT 8 AS RES;
    WHEN (@ETI=1 AND @REF=0 AND @IMG=0) THEN SELECT 1 AS RES;
    WHEN (@ETI=0 AND @REF=1 AND @IMG=0) THEN SELECT 2 AS RES;
    WHEN (@ETI=0 AND @REF=0 AND @IMG=1) THEN SELECT 3 AS RES;
    WHEN (@ETI=1 AND @REF=1 AND @IMG=0) THEN SELECT 4 AS RES;
    WHEN (@ETI=1 AND @REF=0 AND @IMG=1) THEN SELECT 5 AS RES;
    WHEN (@ETI=0 AND @REF=1 AND @IMG=1) THEN SELECT 6 AS RES;     
    WHEN (@ETI=1 AND @REF=1 AND @IMG=1) THEN SELECT 7 AS RES;
    ELSE SELECT 0 AS RES;
  END CASE;
  
END;
