
-- CALL SP_WAPP_PUBLICACION_CONSULTA_CONTENIDO_ARTICULO(30, @codErr);
-- SELECT @codErr;


-- SELECT * FROM PUBLICACION_CONTENIDO WHERE PUID=86;

DROP PROCEDURE IF EXISTS bodyflex.SP_WAPP_PUBLICACION_CONSULTA_CONTENIDO_ARTICULO;
CREATE PROCEDURE bodyflex.`SP_WAPP_PUBLICACION_CONSULTA_CONTENIDO_ARTICULO`(
                                                  IN id VARCHAR(50)
                                                  , OUT codErr INTEGER
                                                 )
BEGIN

DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;
SET codErr=0;
  IF EXISTS(SELECT * FROM PUBLICACION_CONTENIDO WHERE PUID=id)THEN
      SET @urlPrincipal = (SELECT URLCONT FROM PUBLICACION_CONTENIDO WHERE PUID=id AND PRICONT=1 ORDER BY IDCONT ASC LIMIT 1);
      SET @registros = (SELECT COUNT(*) FROM PUBLICACION_CONTENIDO WHERE PUID=id);
      SET @URL = (SELECT PARVAL FROM PARAMETROS WHERE PARNOM='DRIVE');
            
      SELECT TIPCONT
      , URLCONT
      , @urlPrincipal
      , @registros
      , @URL
      FROM PUBLICACION_CONTENIDO
      WHERE PUID=id 
      ORDER BY IDCONT ASC;     
      
  ELSE
    SET codErr=98;
  END IF;

END




