-- CALL SP_WPRO_PERFIL_PROFESIONAL_GET_PRODUCTOS('13661574',0, @codErr);
-- SELECT @codErr;

-- CALL SP_WPRO_PERFIL_PROFESIONAL_GET_PRODUCTOS('13661574',1, @codErr);
-- SELECT @codErr;

-- SELECT * FROM PROFESIONAL_PRODUCTO_CONTENIDO

                                  
DROP PROCEDURE IF EXISTS bodyflex.SP_WPRO_PERFIL_PROFESIONAL_GET_PRODUCTOS;
CREATE PROCEDURE bodyflex.`SP_WPRO_PERFIL_PROFESIONAL_GET_PRODUCTOS`(
                                                                  IN rut VARCHAR(20)
                                                                  , IN prueba INTEGER
                                                                  , OUT codErr INTEGER
                                                                )
BEGIN

-- DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;
SET codErr=0;
-- prueba = [1 | 0] 1=mustra los ingresados, 0=muestra sólo los publicados
-- OBTIENE TODOS LOS PRODUCTOS ASOCIADOS AL PROFESIONAL
-- select * from producto
  IF prueba=0 THEN -- NO ES PRUEBA
    IF EXISTS(SELECT * FROM PRODUCTO P, PRODUCTO_PROFESIONAL PP WHERE P.PROID=PP.PROID AND PP.PRUT=rut AND PROET='PUBLICADO') THEN
      SELECT P.PROID
      , P.PRONO
      , P.PRODE
      , CONCAT('$',REPLACE(FORMAT(PROPV,0),',','.')) AS PRECIO
      , (SELECT PARVAL FROM PARAMETROS WHERE PARNOM='DRIVE') AS URL
      , (SELECT PCO_DRI FROM PRODUCTO_CONTENIDO PPC WHERE PPC.PROID=P.PROID AND PPC.PCO_PRI=1 ORDER BY PCO_ID ASC LIMIT 1) AS DRIVE
      , IFNULL((SELECT PCP1_NOM FROM PRODUCTO_CATEGORIA1 PPC1 WHERE PPC1.PCP1_ID=P.PCP1_ID),0) AS CAT1
      , IFNULL((SELECT PCP2_NOM FROM PRODUCTO_CATEGORIA2 PPC2 WHERE PPC2.PCP2_ID=P.PCP2_ID),0) AS CAT2
      , IFNULL((SELECT PCP3_NOM FROM PRODUCTO_CATEGORIA3 PPC3 WHERE PPC3.PCP3_ID=P.PCP3_ID),0) AS CAT3
      , P.PROES
      , P.PROCO
      , PP.PRUT
      FROM PRODUCTO P, PRODUCTO_PROFESIONAL PP
      WHERE P.PROID=PP.PROID AND PP.PRUT=rut AND P.PROET='PUBLICADO'
      ORDER BY P.PROFP ASC;
    ELSE
      SET codErr=98;  
    END IF;
  ELSE -- ES PRUEBA
    IF EXISTS(SELECT * FROM PRODUCTO P, PRODUCTO_PROFESIONAL PP WHERE P.PROID=PP.PROID AND PP.PRUT=rut) THEN
     
      SELECT P.PROID
      , P.PRONO
      , P.PRODE
      , CONCAT('$',REPLACE(FORMAT(PROPV,0),',','.')) AS PRECIO
      , (SELECT PARVAL FROM PARAMETROS WHERE PARNOM='DRIVE') AS URL
      , (SELECT PCO_DRI FROM PRODUCTO_CONTENIDO PPC WHERE PPC.PROID=P.PROID AND PPC.PCO_PRI=1 ORDER BY PCO_ID ASC LIMIT 1) AS DRIVE
      , IFNULL((SELECT PCP1_NOM FROM PRODUCTO_CATEGORIA1 PPC1 WHERE PPC1.PCP1_ID=P.PCP1_ID),0) AS CAT1
      , IFNULL((SELECT PCP2_NOM FROM PRODUCTO_CATEGORIA2 PPC2 WHERE PPC2.PCP2_ID=P.PCP2_ID),0) AS CAT2
      , IFNULL((SELECT PCP3_NOM FROM PRODUCTO_CATEGORIA3 PPC3 WHERE PPC3.PCP3_ID=P.PCP3_ID),0) AS CAT3
      , P.PROES
      , P.PROCO
      , PP.PRUT
      FROM PRODUCTO P, PRODUCTO_PROFESIONAL PP
      WHERE P.PROID=PP.PROID AND PP.PRUT=rut 
      AND EXISTS(SELECT * FROM PRODUCTO_CONTENIDO WHERE PROID=P.PROID)
      ORDER BY P.PROFI ASC;
    ELSE
      SET codErr=98;   
    END IF;
  END IF;
END




