-- CALL SP_WAPP_CONSULTA_REFERENCIA_FORM_PUBLICACION('999');
-- CALL SP_WAPP_CONSULTA_REFERENCIA_FORM_PUBLICACION('LIB');
-- CALL SP_WAPP_CONSULTA_REFERENCIA_FORM_PUBLICACION('WEB');
-- select * from 


DROP PROCEDURE IF EXISTS delta.SP_WAPP_CONSULTA_REFERENCIA_FORM_PUBLICACION;
CREATE PROCEDURE delta.`SP_WAPP_CONSULTA_REFERENCIA_FORM_PUBLICACION`(
                                                                            IN keyWord VARCHAR(500)
                                                                            ,OUT codErr INTEGER 
                                                                        )
BEGIN

  DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;
  SET codErr=0;
  IF EXISTS(SELECT DISTINCT R.RETIPO FROM PUBLICACION_REFERENCIA PR, PUBLICACION_LIST_REFERENCIA R WHERE PR.REID=R.REID AND R.RETIPO LIKE CONCAT('%',keyWord,'%')) THEN
    SELECT DISTINCT R.RETIPO AS TIPO
    FROM PUBLICACION_REFERENCIA PR, PUBLICACION_LIST_REFERENCIA R
    WHERE PR.REID=R.REID AND R.RETIPO LIKE CONCAT('%',keyWord,'%')
    ORDER BY TIPO ASC;
  ELSE
    SET codErr=98;
  END IF;

END;

-- select * from PUBLICACION_REFERENCIA;
-- select * from PUBLICACION_LIST_REFERENCIA;