-- CALL SP_CONSULTA_REFERENCIAS_ARTICULO(9);
-- SELECT * FROM PUBLICACION_REFERENCIA;

DROP PROCEDURE IF EXISTS bodyflex.SP_WAPP_CONSULTA_REFERENCIAS_ARTICULO;
CREATE PROCEDURE bodyflex.`SP_WAPP_CONSULTA_REFERENCIAS_ARTICULO`(
                                                            IN id VARCHAR(50)
                                                            , OUT codErr INTEGER    
                                                          )
BEGIN 
DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;
SET codErr=0;
  
  SELECT PR.PRID AS 'ID'
  , PR.PRNOM AS 'NOMBRE'
  , (SELECT R.RETIPO FROM PUBLICACION_LIST_REFERENCIA R WHERE R.REID = PR.REID) AS 'TIPO'
  , PR.PRDES AS 'DESCRIPCION'
  FROM PUBLICACION_REFERENCIA PR
  WHERE PR.PUID=id
  ORDER BY PR.PRID ASC;
  
END;




