DROP PROCEDURE IF EXISTS bodyflex.SP_ADMIN_SERVICIO_PROFE_CONSULTA;
DROP PROCEDURE IF EXISTS SP_CONSULTA_PUBLICACION_RSM;
DROP PROCEDURE IF EXISTS SP_CONSULTA_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_WPRO__PERFIL_PROFESIONAL_GET_PRODUCTOS;
DROP PROCEDURE IF EXISTS SP_VERIFICA_IMAGEN_SLIDER;
DROP PROCEDURE IF EXISTS SP_VERIFICA_IMAGEN_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_VERIFICA_IMAGEN_PRESENTACION;
DROP PROCEDURE IF EXISTS SP_VERIFICA_ELIMINA_IMAGEN_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_VERIFICA_ELEMENTOS_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_VALIDA_ELEMENTOS_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_SLIDER_VERIFICA_IMAGEN;
DROP PROCEDURE IF EXISTS SP_SLIDER_INGRESA_MODIFICA;
DROP PROCEDURE IF EXISTS SP_SLIDER_INGRESA_IMAGEN;
DROP PROCEDURE IF EXISTS SP_SLIDER_ELIMINA;
DROP PROCEDURE IF EXISTS SP_SLIDER_CONSULTA;
DROP PROCEDURE IF EXISTS SP_SERVICIO_PROFESIONAL_ELIMINA;
DROP PROCEDURE IF EXISTS SP_SERVICIO_PROFESIONAL_AGREGA;
DROP PROCEDURE IF EXISTS SP_SERVICIO_OBTIENE_DETALLE;
DROP PROCEDURE IF EXISTS SP_SERVICIO_OBTIENE;
DROP PROCEDURE IF EXISTS SP_SERVICIO_CUENTA_VISITA;
DROP PROCEDURE IF EXISTS SP_SEGUIR_PROFESIONAL;
DROP PROCEDURE IF EXISTS SP_RU_INGRESA_USUARIO;
DROP PROCEDURE IF EXISTS SP_RC_ASOCIA_CODIGO;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_VERIFICA_IMAGEN;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_VERIFICA_ELEMENTOS;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_VALIDA_ELEMENTOS;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_PUBLICAR;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_POSEE_CONTENIDO;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_OBTIENE_ETIQUETAS_X_CATEGORIA;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_OBTENER_BAJADA;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_OBTENER;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_INGRESA_REFERENCIA;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_INGRESA_MODIFICA_CONTENIDO;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_INGRESA_MODIFICA;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_INGRESA_ETIQUETA_EN_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_INGRESA_ETIQUETA;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_INGRESA_CATEGORIA_ETIQUETA;


DROP PROCEDURE IF EXISTS SP_AGREGA_COMENTARIO_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_PRESENTACION_VERIFICA_IMAGEN;
DROP PROCEDURE IF EXISTS SP_PROFESIONAL_ADD_CARRITO;
DROP PROCEDURE IF EXISTS SP_PROFESIONAL_CUENTA_CONTACTO;
DROP PROCEDURE IF EXISTS SP_PROFESIONAL_ELIMINA_PRODUCTO;
DROP PROCEDURE IF EXISTS SP_PROFESIONAL_GET_CANT_PRODUCTOS_CART;
DROP PROCEDURE IF EXISTS SP_PROFESIONAL_GET_PRODUCTOS_CART;
DROP PROCEDURE IF EXISTS SP_PROFESIONAL_INGRESA_MODIFICA_PRODUCTOS;
DROP PROCEDURE IF EXISTS SP_PROFESIONAL_PRODUCTO_ELIMINA_CONTENIDO;
DROP PROCEDURE IF EXISTS SP_PROFESIONAL_PRODUCTO_INGRESA_MODIFICA_CONTENIDO;
DROP PROCEDURE IF EXISTS SP_PROFESIONAL_PRODUCTO_CONSULTA_CONTENIDO;
DROP PROCEDURE IF EXISTS SP_PROFESIONAL_PRODUCTO_VERIFICA_CONTENIDO;
DROP PROCEDURE IF EXISTS SP_PROFESIONAL_PRODUCTO_PUBLICAR;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_CONSULTA_CONTENIDO;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_CONSULTA_ETIQUETA_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_CONSULTA_CONTENIDO_ARTICULO;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_ELIMINA;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_ELIMINA_CONTENIDO;
DROP PROCEDURE IF EXISTS SP_INGRESA_MODIFICA_CURRICULUM_OTROS;
DROP PROCEDURE IF EXISTS SP_PERFIL_PROFESIONAL_GET_SLIDER;
DROP PROCEDURE IF EXISTS SP_PORTAFOLIO_CONSULTA;
DROP PROCEDURE IF EXISTS SP_PORTAFOLIO_VERIFICA_IMAGEN;
DROP PROCEDURE IF EXISTS SP_PERFIL_PROFESIONAL_GET_SERVICIOS;
DROP PROCEDURE IF EXISTS SP_PORTAFOLIO_ELIMINA;
DROP PROCEDURE IF EXISTS SP_PORTAFOLIO_INGRESA_IMAGEN;
DROP PROCEDURE IF EXISTS SP_PRESENTACION_INGRESA_IMAGEN;
DROP PROCEDURE IF EXISTS SP_PROFESIONAL_GET_IMG_PRO;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_CONSULTA_CATEGORIA_ETIQUETA;
DROP PROCEDURE IF EXISTS SP_AGREGA_VOTACION_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_PERFIL_PROFESIONAL_GET_DETALLE_PRODUCTO;
DROP PROCEDURE IF EXISTS SP_PERFIL_PROFESIONAL_POSEE_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_PERFIL_PROFESIONAL_GET_PRODUCTOS;
DROP PROCEDURE IF EXISTS SP_PERFIL_PROFESIONAL_GET_PUBLICACIONES;
DROP PROCEDURE IF EXISTS SP_PERFIL_PROFESIONAL_POSEE_PROD;
DROP PROCEDURE IF EXISTS SP_PRESENTACION_ELIMINA;
DROP PROCEDURE IF EXISTS SP_PRESENTACION_CONSULTA;
DROP PROCEDURE IF EXISTS SP_PROFESIONAL_PRODUCTO_CUENTA_VISITA;
DROP PROCEDURE IF EXISTS SP_AGREGA_VOTACION_PROFESIONAL;
DROP PROCEDURE IF EXISTS SP_MUESTRA_S1;
DROP PROCEDURE IF EXISTS SP_ELIMINA_ETIQUETA;
DROP PROCEDURE IF EXISTS SP_OTROS_CONSULTA;
DROP PROCEDURE IF EXISTS SP_PERFIL_PROFESIONAL_DEL_PRO_CART;
DROP PROCEDURE IF EXISTS SP_PERFIL_PROFESIONAL_GET_DET_PRODUCTOS;
DROP PROCEDURE IF EXISTS SP_PERFIL_PROFESIONAL_GET_RSM_CURRICULUM;
DROP PROCEDURE IF EXISTS SP_ELIMINA_CURRICULUM_ESTUDIOS;
DROP PROCEDURE IF EXISTS SP_AGREGA_VOTACION_SERVICIO;
DROP PROCEDURE IF EXISTS SP_ELIMINA_CURRICULUM;
DROP PROCEDURE IF EXISTS SP_PERFIL_PROFESIONAL_GET_DATA_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_CONSULTA_REFERENCIAS_ASOCIADAS;
DROP PROCEDURE IF EXISTS SP_CP_COM_MENSAJE_SET_COMO_LEIDO;
DROP PROCEDURE IF EXISTS SP_MENSAJE_INGRESA_RESPUESTA;
DROP PROCEDURE IF EXISTS SP_EXPERIENCIA_INGRESA_MODIFICA;
DROP PROCEDURE IF EXISTS SP_ELIMINA_EXPERIENCIA;
DROP PROCEDURE IF EXISTS SP_MODIFICA_SLIDER;
DROP PROCEDURE IF EXISTS SP_CONSULTA_CURRICULUM_OTROS;
DROP PROCEDURE IF EXISTS SP_DENUNCIAR_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_INGRESA_MODIFICA_BODY_PORTAFOLIO;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_CONSULTA;
DROP PROCEDURE IF EXISTS SP_ELIMINA_ALL_ETIQUETA_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_ELIMINA_CATEGORIA_ETIQUETA;
DROP PROCEDURE IF EXISTS SP_INGRESA_MODIFICA_CURRCULUM;
DROP PROCEDURE IF EXISTS SP_PRESENTACION_INGRESA_MODIFICA;
DROP PROCEDURE IF EXISTS SP_INGRESA_ETIQUETA_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_OTROS_INGRESA_MODIFIC;
DROP PROCEDURE IF EXISTS SP_INGRESA_MODIFICA_BODY_SERVICIO;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_CONSULTA_ETIQUETA2;
DROP PROCEDURE IF EXISTS SP_ELIMINA_COMENTARIO_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_CP_USR_MENSAJE_INGRESA_RESPUESTA;
DROP PROCEDURE IF EXISTS SP_INGRESA_PUBLICACION_REFERENCIA;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_ELIMINA_CATEGORIA_ETIQUETA;
DROP PROCEDURE IF EXISTS SP_ELIMINA_CURRICULUM_OTROS;
DROP PROCEDURE IF EXISTS SP_CUR_GET_EXP;
DROP PROCEDURE IF EXISTS SP_INGRESA_SLIDER;
DROP PROCEDURE IF EXISTS SP_ELIMINA_ETIQUETA_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_PERFIL_PROFESIONAL_GET_PORTAFOLIO;
DROP PROCEDURE IF EXISTS SP_ELIMINA_BODY_SERVICIO;
DROP PROCEDURE IF EXISTS SP_ELIMINA_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_ELIMINA_ETIQUETA;
DROP PROCEDURE IF EXISTS SP_CONSULTA_VOTACION_PROFESIONAL_PRODUCTO;
DROP PROCEDURE IF EXISTS SP_CUR_GET_BIO;
DROP PROCEDURE IF EXISTS SP_INGRESA_MODIFICA_PRESENTACION;
DROP PROCEDURE IF EXISTS SP_CP_ADM_INGRESA_MODIFICA_PRODUCTOS;
DROP PROCEDURE IF EXISTS SP_ELIMINA_HEAD_SERVICIO;
DROP PROCEDURE IF EXISTS SP_INGRESA_MODIFICA_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_CP_ADM_MOD_EST_POS_EVALUANDO;
DROP PROCEDURE IF EXISTS SP_CUR_GET_OTR;
DROP PROCEDURE IF EXISTS SP_OBTIENE_ETIQUETAS_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_AGREGA_VOTACION_PROFESIONAL_PRODUCTO;
DROP PROCEDURE IF EXISTS SP_INGRESA_MODIFICA_CURRICULUM_ESTUDIOS;
DROP PROCEDURE IF EXISTS SP_CONSULTA_REFERENCIAS_ARTICULO;
DROP PROCEDURE IF EXISTS SP_INGRESA_MODIFICA_EXPERIENCIA;
DROP PROCEDURE IF EXISTS SP_CONSULTA_HEAD_SERVICIO;
DROP PROCEDURE IF EXISTS SP_INGRESA_MODIFICA_HEAD_PORTAFOLIO;
DROP PROCEDURE IF EXISTS SP_CONSULTA_ETIQUETA_PUBLICACION_RSM;
DROP PROCEDURE IF EXISTS SP_CONSULTA_CATEGORIA_ETIQUETA;
DROP PROCEDURE IF EXISTS SP_INGRESA_MENSAJE_PROFESIONAL;
DROP PROCEDURE IF EXISTS SP_CONSULTA_PUBLICACION_RSM;
DROP PROCEDURE IF EXISTS SP_CARRO_ADD_REDUCE;
DROP PROCEDURE IF EXISTS SP_INGRESA_IMAGEN_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_CP_PRO_CSU_PRO_POS_APR;
DROP PROCEDURE IF EXISTS SP_PERFIL_PROFESIONAL_GET_PRESENTACION;
DROP PROCEDURE IF EXISTS SP_CONSULTA_REFERENCIA_FORM_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_ELIMINA_CURRICULUM_EXPERIENCIA;
DROP PROCEDURE IF EXISTS SP_CONSULTA_CURRICULUM_ESTUDIOS;
DROP PROCEDURE IF EXISTS SP_CONSULTA_PUBLICACION_SEGUIR;
DROP PROCEDURE IF EXISTS SP_MENSAJE_OBTIENE_DETALLE;
DROP PROCEDURE IF EXISTS SP_CARRO_DEL_PROD;
DROP PROCEDURE IF EXISTS SP_INGRESA_MODIFICA_HEADSERVICIO;
DROP PROCEDURE IF EXISTS SP_CONSULTA_ARTICULO_PROFESIONAL;
DROP PROCEDURE IF EXISTS SP_CONSULTA_REFERENCIA;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_CUENTA_VISITA;
DROP PROCEDURE IF EXISTS SP_CP_COM_MENSAJE_OBTIENE_DETALLE;
DROP PROCEDURE IF EXISTS SP_CP_ADM_REG_MOD_PRO;
DROP PROCEDURE IF EXISTS SP_CONSULTA_COMENTARIOS_PUBLICACION2;
DROP PROCEDURE IF EXISTS SP_CONSULTA_COMENTARIOS_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_INGRESA_MODIFICA_CURRICULUM_EXPERIENCIA;
DROP PROCEDURE IF EXISTS SP_CONSULTA_ACTEGORIA_FORM_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_EXPERIENCIA_ELIMINA;
DROP PROCEDURE IF EXISTS SP_CONSULTA_PRESENTACION;
DROP PROCEDURE IF EXISTS SP_OTROS_ELIMINA;
DROP PROCEDURE IF EXISTS SP_CARRO_GET_DAT_PRO;
DROP PROCEDURE IF EXISTS SP_ESTUDIOS_ELIMINA;
DROP PROCEDURE IF EXISTS SP_CONSULTA_BODY_PORTAFOLIO;
DROP PROCEDURE IF EXISTS SP_INGRESA_ETIQUETA;
DROP PROCEDURE IF EXISTS SP_CONSULTA_BODY_SERVICIOS;
DROP PROCEDURE IF EXISTS SP_INGRESA_HEAD_SERVICIO;
DROP PROCEDURE IF EXISTS SP_CONSULTA_CATEGORIA_ETIQUETA2;
DROP PROCEDURE IF EXISTS SP_CONSULTA_DENUNCIA_PROFESIONAL_PRODUCTO;
DROP PROCEDURE IF EXISTS SP_CONSULTA_CATEGORIA_FORM_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_INGRESA_MODIFICA_SLIDER;
DROP PROCEDURE IF EXISTS SP_INGRESA_REFERENCIA;
DROP PROCEDURE IF EXISTS SP_CONSULTA_CATEGORIAS_PRODUCTOS;
DROP PROCEDURE IF EXISTS SP_INGRESA_MODIFICA_OTROS;
DROP PROCEDURE IF EXISTS SP_CONSULTA_CURRICULUM;
DROP PROCEDURE IF EXISTS SP_MENSAJE_PROFESIONAL_CONSULTA;
DROP PROCEDURE IF EXISTS SP_CONSULTA_CURRICULUM_EXPERIENCIA;
DROP PROCEDURE IF EXISTS SP_PERFIL_PROFESIONAL_GET_DET_SERVICIO;
DROP PROCEDURE IF EXISTS SP_INGRESA_HEAD_SERVICIO;
DROP PROCEDURE IF EXISTS SP_CONSULTA_DENUNCIA_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_ELIMINA_ALL_ETIQUETA;
DROP PROCEDURE IF EXISTS SP_CONSULTA_ESTUDIOS;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_ELIMINA_ETIQUETA_DE_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_CONSULTA_ETIQUETA;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_ELIMINA_REFERENCIA_ASOCIADA;
DROP PROCEDURE IF EXISTS SP_CONSULTA_ETIQUETA_ARTICULO;
DROP PROCEDURE IF EXISTS SP_CONSULTA_ETIQUETA_FORM_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_CONSULTA_ETIQUETA_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_CONSULTA_EXPERIENCIA;
DROP PROCEDURE IF EXISTS SP_CONSULTA_HEAD_PORTAFOLIO;
DROP PROCEDURE IF EXISTS SP_CONSULTA_OTROS;
DROP PROCEDURE IF EXISTS SP_CONSULTA_PROF_FORM_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_CONSULTA_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_CONSULTA_PUBLICACION_DENUNCIA;
DROP PROCEDURE IF EXISTS SP_CONSULTA_REFERENCIAS_ASOCIADAS;
DROP PROCEDURE IF EXISTS SP_CONSULTA_S1;
DROP PROCEDURE IF EXISTS SP_CONSULTA_SERVICIOS;
DROP PROCEDURE IF EXISTS SP_CONSULTA_SLIDER;
DROP PROCEDURE IF EXISTS SP_CONSULTA_TITULO_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_CONSULTA_VOTACION_PROFESIONAL;
DROP PROCEDURE IF EXISTS SP_CONSULTA_VOTACION_PUBLICACION;
DROP PROCEDURE IF EXISTS SP_CP_ADM_CONSULTA_POSTULACION;
DROP PROCEDURE IF EXISTS SP_CP_COM_MENSAJE_INGRESA_RESPUESTA;
DROP PROCEDURE IF EXISTS SP_CP_COM_MENSAJE_PROFESIONAL_CONSULTA;
DROP PROCEDURE IF EXISTS SP_CP_PRO_PORTAFOLIO_INGRESA_MODIFICA;
DROP PROCEDURE IF EXISTS SP_CP_USR_MENSAJE_OBTIENE_DETALLE;
DROP PROCEDURE IF EXISTS SP_CP_USR_MENSAJE_PROFESIONAL_CONSULTA;
DROP PROCEDURE IF EXISTS SP_CUR_GET_EST;
DROP PROCEDURE IF EXISTS SP_DENUNCIAR_PRODUCTO_PROFESIONAL;
DROP PROCEDURE IF EXISTS SP_DENUNCIAR_PROFESIONAL;
DROP PROCEDURE IF EXISTS SP_ELIMINA_BODY_PORTAFOLIO;
DROP PROCEDURE IF EXISTS SP_ELIMINA_HEAD_PORTAFOLIO;
DROP PROCEDURE IF EXISTS SP_ELIMINA_PRESENTACION;
DROP PROCEDURE IF EXISTS SP_ELIMINA_REFERENCIA_ASOCIADA;
DROP PROCEDURE IF EXISTS SP_ELIMINA_S1;
DROP PROCEDURE IF EXISTS SP_ELIMINA_SLIDER;
DROP PROCEDURE IF EXISTS SP_ESTUDIOS_CONSULTA;
DROP PROCEDURE IF EXISTS SP_ESTUDIOS_INGRESA_MODIFICA;
DROP PROCEDURE IF EXISTS SP_EXPERIENCIA_CONSULTA;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_ELIMINA_ALL_ETIQUETA;
DROP PROCEDURE IF EXISTS SP_PERFIL_PROFESIONAL_GET_PRO_CART;
DROP PROCEDURE IF EXISTS SP_INGRESA_MODIFICA_S1;
DROP PROCEDURE IF EXISTS SP_MENSAJE_SET_COMO_LEIDO;
DROP PROCEDURE IF EXISTS SP_LOGIN;
DROP PROCEDURE IF EXISTS SP_INGRESA_CATEGORIA_ETIQUETA;
DROP PROCEDURE IF EXISTS SP_INGRESA_IMAGEN_SLIDER;
DROP PROCEDURE IF EXISTS SP_INGRESA_IMAGEN_PRESENTACION;

DROP PROCEDURE IF EXISTS SP_ADM_SERVICIO_PROFE_CONSULTA;
DROP PROCEDURE IF EXISTS SP_ADM_SERVICIO_PROFE_ELIMINA;
DROP PROCEDURE IF EXISTS SP_ADM_SERVICIO_PROFE_INGRESA_IMAGEN;
DROP PROCEDURE IF EXISTS SP_ADM_SERVICIO_PROFE_INGRESA_MODIFICA;
DROP PROCEDURE IF EXISTS SP_ADM_SERVICIO_PROFE_VERIFICA_IMAGEN;
DROP PROCEDURE IF EXISTS SP_CONSULTA_VOTACION_SERVICIO;
DROP PROCEDURE IF EXISTS SP_ELIMINA_ESTUDIOS;
DROP PROCEDURE IF EXISTS SP_INGRESA_MODIFICA_ESTUDIOS;
DROP PROCEDURE IF EXISTS SP_PROFESIONAL_CONSULTA_PRODUCTO;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_CONSULTA_CATEGORIA_ETIQUETA2;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_CONSULTA_REFERENCIA;
DROP PROCEDURE IF EXISTS SP_PUBLICACION_INGRESA_IMAGEN;
DROP PROCEDURE IF EXISTS SP_SERVICIO_PROFESIONAL_OBTIENE_TODOS;


















































































































