-- CALL SP_CUR_GET_BIO('9386703');
-- SELECT * FROM PROFESIONAL;
-- SELECT * FROM PORTAFOLIO;
-- SELECT * FROM PARAMETROS;

DROP PROCEDURE IF EXISTS bodyflex.SP_CUR_GET_BIO;
CREATE PROCEDURE bodyflex.`SP_CUR_GET_BIO`(IN rut VARCHAR(20))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';

  IF EXISTS(SELECT * FROM ESTUDIOS WHERE PRUT = rut) THEN
    
    SET @NOM = (SELECT CONCAT(PNOM1,' ',PNOM2,' ',PAPE1,' ',PAPE2) FROM PROFESIONAL WHERE PRUT=rut);
    SET @TIP = (SELECT PTIPO2 FROM PROFESIONAL WHERE PRUT=rut);
    SET @ESP = (SELECT PESP FROM PROFESIONAL WHERE PRUT=rut);
    SET @PRE = (SELECT PTXTOPRE FROM PROFESIONAL WHERE PRUT=rut);
    SET @PAR = (SELECT PARVAL FROM PARAMETROS WHERE PARNOM='DRIVE');
    SET @REG = (SELECT COUNT(*) FROM PORTAFOLIO WHERE PRUT=rut);
      
    SELECT @NOM AS 'NOM'
    , @TIP AS 'TIP'
    , @ESP AS 'ESP'
    , @PRE AS 'PRE'
    , @PAR AS 'DRI'
    , PONOMCAP
    , POIDFLI
    , @REG
    FROM PORTAFOLIO
    WHERE PRUT=rut;
    
  ELSE
    SELECT 98;    
  END IF;
  
END




