-- CALL SP_OTROS_CONSULTA('9386703');
-- SELECT * FROM PROFESIONAL;
-- SELECT * FROM OTRO;

DROP PROCEDURE IF EXISTS bodyflex.SP_OTROS_CONSULTA;
CREATE PROCEDURE bodyflex.`SP_OTROS_CONSULTA`(IN rut VARCHAR(20))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';

  IF EXISTS(SELECT * FROM OTROS WHERE PRUT = rut) THEN
    SELECT OTID
    , OTNOM
    , OTTIPO
    , OTDES
    , DATE_FORMAT(OTFECHA,'%d-%m-%Y') as OTFECHA
    , OTPOS
    FROM OTROS
    WHERE PRUT=rut
    ORDER BY OTID DESC;
  ELSE
    SELECT 98;    
  END IF;
  
END




