
-- CALL SP_PUBLICACION_ELIMINA_ETIQUETA('32','CATEGORIA1','CAT1_ETI1');
-- CALL SP_PUBLICACION_ELIMINA_ETIQUETA('32','','');

-- SELECT * FROM PROFESIONAL
-- SELECT * FROM PUBLICACION
-- SELECT * FROM CATEGORIA_ETIQUETA
-- SELECT * FROM PUBLICACION_ETIQUETA
-- SELECT * FROM PUBLICACION_LIST_ETIQUETAS




DROP PROCEDURE IF EXISTS bodyflex.SP_PUBLICACION_ELIMINA_ETIQUETA;
CREATE PROCEDURE bodyflex.`SP_PUBLICACION_ELIMINA_ETIQUETA`( 
                                                                IN rut VARCHAR(10)
                                                                , IN cat VARCHAR(50)
                                                                , IN eti VARCHAR(50)
                                                            )
BEGIN
  
  -- [ELIMINA ETIQUETA DEL LOISTADO DE ETIQUETAS]
  DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';
  
  IF EXISTS(SELECT * FROM PUBLICACION_LIST_ETIQUETAS WHERE ETRUT=rut AND CATETINOM=cat AND ETNOM=eti) THEN 
    IF NOT EXISTS(SELECT * FROM PUBLICACION_ETIQUETA PE, PUBLICACION P WHERE PE.PUID=P.PUID AND P.PUEST='INACTIVO' AND CATETINOM=cat AND ETNOM=eti) THEN
      IF EXISTS(SELECT * FROM PUBLICACION_ETIQUETA PE, PUBLICACION P WHERE PE.PUID=P.PUID AND PE.CATETINOM=cat AND PE.ETNOM=eti) THEN
        DELETE FROM PUBLICACION_ETIQUETA WHERE CATETINOM=cat AND ETNOM=eti;
        DELETE FROM PUBLICACION_LIST_ETIQUETAS WHERE ETRUT=rut AND CATETINOM=cat AND ETNOM=eti ;
        SELECT 1;
      ELSE
        DELETE FROM PUBLICACION_LIST_ETIQUETAS WHERE ETRUT=rut AND CATETINOM=cat AND ETNOM=eti ;
        SELECT 1;
      END IF;
    ELSE
      SELECT 96; -- NO ES POSIBLE ELIMINAR ETIQUETA ASOCIADA A UNA PUBLICACIÓN EN ESTADO DISTINTO DE 'INACTIVO'
    END IF;
  ELSE
    SELECT 97; -- SOLO EL CREADOR DE LA ETIQUETA LA PUEDE ELIMINAR  
  END IF;
  
    
   
      
END;


-- select * from PUBLICACION_ETIQUETA;