
-- CALL SP_ADM_SERVICIO_PROFE_ELIMINA('12');
   
-- SELECT * FROM SERVICIO;

DROP PROCEDURE IF EXISTS bodyflex.SP_ADM_SERVICIO_PROFE_ELIMINA;
CREATE PROCEDURE bodyflex.`SP_ADM_SERVICIO_PROFE_ELIMINA`(IN id VARCHAR(20))
BEGIN

DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';  
  
  DELETE FROM SERVICIO WHERE SEID=id;    
  SELECT 1;
  
END;
