-- CALL SP_PERFIL_PROFESIONAL_GET_DET_SERVICIO(9386703,53);
-- SELECT * FROM PROFESIONAL;
-- SELECT * FROM PROFESIONAL_SERVICIO;
-- SELECT * FROM SERVICIO;

DROP PROCEDURE IF EXISTS bodyflex.SP_PERFIL_PROFESIONAL_GET_DET_SERVICIO;
CREATE PROCEDURE bodyflex.`SP_PERFIL_PROFESIONAL_GET_DET_SERVICIO`(
                                                                    IN rut VARCHAR(20)
                                                                    , IN id VARCHAR(20)
                                                                  )
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';

SET @URL = (SELECT PARVAL FROM PARAMETROS WHERE PARNOM='DRIVE');
SET @IMGPRO = (SELECT PFOTOPRE FROM PROFESIONAL WHERE PRUT=rut);
SET @NOMPRO = (SELECT CONCAT(PNOM1,' ',PAPE1) FROM PROFESIONAL WHERE PRUT=rut);
SET @TIPPRO = (SELECT PTIPO2 FROM PROFESIONAL WHERE PRUT=rut);
        
    SELECT SEID
    , SENOM
    , SEDESLAR
    , SEIDFLI
    , @URL AS URL
    , @IMGPRO AS IMGPRO
    , @NOMPRO AS NOMPRO
    , @TIPPRO AS TIPO
    FROM SERVICIO
    WHERE SEID=id;
  
END




