
-- CALL SP_PRESENTACION_CONSULTA('13661574');
-- SELECT * FROM PROFESIONAL WHERE PRUT='13661574';
-- SELECT PTXTOPRE FROM PROFESIONAL WHERE PRUT='13661574';

DROP PROCEDURE IF EXISTS bodyflex.SP_PRESENTACION_CONSULTA;
CREATE PROCEDURE bodyflex.`SP_PRESENTACION_CONSULTA`(IN rut VARCHAR(20))
BEGIN

  SET @texto=(SELECT PTXTOPRE FROM PROFESIONAL WHERE PRUT=rut);
  SET @texto=TRIM(IFNULL(@texto,'0'));

  IF @texto<>'0' and @texto<>'' THEN
    SELECT PFOTOPRE, PTXTOPRE, PIDFOTOFLICKR FROM PROFESIONAL WHERE PRUT=rut;
  ELSE
    SELECT 2;
  END IF;
 
END;
