-- CALL SP_PERFIL_PROFESIONAL_GET_DET_PRODUCTOS('4','9386703');
-- SELECT * FROM PROFESIONAL_PRODUCTO

DROP PROCEDURE IF EXISTS bodyflex.SP_PERFIL_PROFESIONAL_GET_DET_PRODUCTOS;
CREATE PROCEDURE bodyflex.`SP_PERFIL_PROFESIONAL_GET_DET_PRODUCTOS`(
                                                                  IN id VARCHAR(20)
                                                                  , IN rut VARCHAR(20)
                                                                )
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';

  IF EXISTS(SELECT * FROM profesional_producto WHERE PROPEST='PUBLICADO' AND PROPID=id AND PRUT=rut) THEN
    SELECT proPNom AS NOMPRO
    , proPMar AS MARCA
    , proPID AS CODPRO
    , PROPCON AS CONPRO
    , CONCAT('$',REPLACE(FORMAT(PROPPREBRU,0),',','.')) AS PRENET
    , CONCAT('$',REPLACE(FORMAT(PROPPREREF,0),',','.')) AS PREREF
    , PROPDESLAR AS PRODES
    , (SELECT pco_dri FROM PROFESIONAL_PRODUCTO_CONTENIDO PPC WHERE PP.PROPEST='PUBLICADO' AND PPC.PROPID=PP.proPID AND PCO_PRI=1) AS IMGPRI
    , (SELECT PARVAL FROM PARAMETROS WHERE PARNOM='DRIVE') AS URL
    , (SELECT pcp1_nom FROM PROFESIONAL_PRODUCTO_CATEGORIA1 ppc1 WHERE ppc1.PCP1_ID=PP.PCP1_ID) AS CATPRO
    FROM PROFESIONAL_PRODUCTO PP     
    WHERE PP.proPID=id AND PP.PRUT=rut; 
  ELSE
    SELECT 98;    
  END IF;

END




