-- CALL SP_CONSULTA_ETIQUETA_PUBLICACION('32');

-- SELECT * FROM PROFESIONAL;
-- SELECT * FROM CATEGORIA_ETIQUETA;
-- SELECT * FROM ETIQUETA;
-- SELECT * FROM PUBLICACION_ETIQUETA;


DROP PROCEDURE IF EXISTS bodyflex.SP_CONSULTA_ETIQUETA_PUBLICACION;
CREATE PROCEDURE bodyflex.`SP_CONSULTA_ETIQUETA_PUBLICACION`(
                                                  IN id VARCHAR(50)
                                                 )
BEGIN

    SELECT ETNOM
    , CATETINOM
    FROM PUBLICACION_ETIQUETA
    WHERE PUID=id
    ORDER BY ETNOM ASC;
    
END




