DROP PROCEDURE IF EXISTS bodyflex.SP_PUBLICACION_VERIFICA_IMAGEN;
CREATE PROCEDURE bodyflex.`SP_PUBLICACION_VERIFICA_IMAGEN`( IN id VARCHAR(100) )
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';
  IF EXISTS(SELECT * FROM PUBLICACION WHERE PUID=id AND puPosImg=1)THEN
    SET @NOMIMG = (SELECT PUNOMIMG FROM PUBLICACION WHERE PUID=id AND puPosImg=1);   
    SELECT 1, @NOMIMG;
  ELSE
    SELECT 2, '';
  END IF;
      
END;
