-- CALL SP_CONSULTA_CATEGORIAS_PRODUCTOS(1,0);
-- CALL SP_CONSULTA_CATEGORIAS_PRODUCTOS(2,1);
-- CALL SP_CONSULTA_CATEGORIAS_PRODUCTOS(2,2);
-- CALL SP_CONSULTA_CATEGORIAS_PRODUCTOS(2,3);
-- CALL SP_CONSULTA_CATEGORIAS_PRODUCTOS(3,4);
-- &#209;
-- SELECT * FROM PROFESIONAL_PRODUCTO_CATEGORIA1
-- SELECT * FROM PROFESIONAL_PRODUCTO_CATEGORIA2
-- SELECT * FROM PROFESIONAL_PRODUCTO_CATEGORIA3

DROP PROCEDURE IF EXISTS bodyflex.SP_CONSULTA_CATEGORIAS_PRODUCTOS;
CREATE PROCEDURE bodyflex.`SP_CONSULTA_CATEGORIAS_PRODUCTOS`(
                                                    IN nivelCat INTEGER
                                                    , IN nivelCod INTEGER
                                                 )
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';

  CASE nivelCat
    WHEN 1 THEN
      IF EXISTS(SELECT * FROM PROFESIONAL_PRODUCTO_CATEGORIA1) THEN
        SELECT PCP1_ID, PCP1_NOM FROM PROFESIONAL_PRODUCTO_CATEGORIA1 ORDER BY PCP1_NOM ASC;
      ELSE
        SELECT 98;
      END IF;
    WHEN 2 THEN
      IF EXISTS(SELECT * FROM PROFESIONAL_PRODUCTO_CATEGORIA2 WHERE PCP1_ID=nivelCod) THEN
        SELECT PCP2_ID, PCP2_NOM FROM PROFESIONAL_PRODUCTO_CATEGORIA2 WHERE PCP1_ID=nivelCod ORDER BY PCP2_NOM ASC;
      ELSE
        SELECT 98;
      END IF;
    WHEN 3 THEN
      IF EXISTS(SELECT * FROM PROFESIONAL_PRODUCTO_CATEGORIA3 WHERE PCP2_ID=nivelCod) THEN
        SELECT PCP3_ID, PCP3_NOM FROM PROFESIONAL_PRODUCTO_CATEGORIA3 WHERE PCP2_ID=nivelCod ORDER BY PCP3_NOM ASC;
      ELSE
        SELECT 98;
      END IF;
  END CASE;
  
END




