
-- select * from profesional
-- call SP_EXPERIENCIA_CONSULTA('9386703');

DROP PROCEDURE IF EXISTS bodyflex.SP_EXPERIENCIA_CONSULTA;
CREATE PROCEDURE bodyflex.`SP_EXPERIENCIA_CONSULTA`(IN rut VARCHAR(20))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';

  IF EXISTS(SELECT * FROM EXPERIENCIA WHERE PRUT = rut) THEN
       
      SELECT EXID
      , EXCARGO
      , EXINS
      , DATE_FORMAT(EXFECDES,'%b %Y') AS EXFECDES
      , DATE_FORMAT(EXFECHAS,'%b %Y') AS EXFECHAS
      , EXPOS
      , EXDES
      , EXTA
      FROM EXPERIENCIA
      WHERE PRUT = rut
      ORDER BY EXPOS ASC;
      
  ELSE
    
    SELECT 98;    
    
  END IF;
  
END;
