-- CALL SP_ELIMINA_CURRICULUM_EXPERIENCIA('25');
   
-- SELECT * FROM ESTUDIOS;

DROP PROCEDURE IF EXISTS bodyflex.SP_ELIMINA_CURRICULUM_EXPERIENCIA;
CREATE PROCEDURE bodyflex.`SP_ELIMINA_CURRICULUM_EXPERIENCIA`(IN id VARCHAR(20))
BEGIN
  
    DELETE FROM EXPERIENCIA WHERE EXID=id;    
    SELECT 1;
          
END;
