
-- select * from servicio

-- CALL SP_ADMIN_SERVICIO_PROFE_CONSULTA();

DROP PROCEDURE IF EXISTS bodyflex.SP_ADMIN_SERVICIO_PROFE_CONSULTA;
CREATE PROCEDURE bodyflex.`SP_ADMIN_SERVICIO_PROFE_CONSULTA`()
BEGIN
  
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';  
  
  IF EXISTS(SELECT * FROM SERVICIO) THEN
  
    SET @CANT=(SELECT COUNT(*) FROM SERVICIO);
    SELECT SEID
      , SENOM
      , SEDESCOR
      , SEDESLAR
      , SEIMGAWE
      , SEIMGSER
      , SEIDFLI
      , @CANT
      FROM SERVICIO
      ORDER BY SEID DESC;
  
  ELSE
  
    SELECT 'X';    
  
  END IF;    
END;
