
-- CALL SP_PORTAFOLIO_ELIMINA('26');
   
-- SELECT * FROM PORTAFOLIO;

DROP PROCEDURE IF EXISTS bodyflex.SP_PORTAFOLIO_ELIMINA;
CREATE PROCEDURE bodyflex.`SP_PORTAFOLIO_ELIMINA`(IN id VARCHAR(20))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';
  
  -- IF EXISTS(SELECT * FROM PORTAFOLIO WHERE POID=id) THEN
      DELETE FROM PORTAFOLIO WHERE POID=id;    
      SELECT 1;
  -- ELSE
    -- SELECT 98;
  -- END IF;
  
END;
