
-- CALL SP_PUBLICACION_ELIMINA_ALL_ETIQUETA('32');

-- SELECT * FROM PROFESIONAL
-- SELECT * FROM PUBLICACION
-- SELECT * FROM CATEGORIA_ETIQUETA
-- SELECT * FROM ETIQUETA
-- SELECT * FROM PUBLICACION_ETIQUETA

DROP PROCEDURE IF EXISTS bodyflex.SP_PUBLICACION_ELIMINA_ALL_ETIQUETA;
CREATE PROCEDURE bodyflex.`SP_PUBLICACION_ELIMINA_ALL_ETIQUETA`(IN id VARCHAR(50))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';
  DELETE FROM PUBLICACION_ETIQUETA WHERE PUID=id;
  SELECT 1;
END;


-- select * from PUBLICACION_ETIQUETA;