-- CALL SP_CONSULTA_EXPERIENCIA('13661574');
-- SELECT * FROM PROFESIONAL;
-- SELECT * FROM CURRICULUM;
-- SELECT * FROM EXPERIENCIA;

DROP PROCEDURE IF EXISTS bodyflex.SP_CONSULTA_EXPERIENCIA;
CREATE PROCEDURE bodyflex.`SP_CONSULTA_EXPERIENCIA`(IN rut VARCHAR(20))
BEGIN

  IF EXISTS(SELECT * FROM EXPERIENCIA WHERE PRUT = rut) THEN
       
      SELECT EXID
      , EXCARGO
      , EXINS
      , EXFECDES
      , EXFECHAS
      , EXPOS
      , EXDES
      FROM EXPERIENCIA
      WHERE PRUT = rut
      ORDER BY EXID DESC;
      
  ELSE
    
    SELECT 'X';    
    
  END IF;
  
END




