
-- CALL SP_SLIDER_ELIMINA('12');
   
-- SELECT * FROM SLIDER;

DROP PROCEDURE IF EXISTS bodyflex.SP_SLIDER_ELIMINA;
CREATE PROCEDURE bodyflex.`SP_SLIDER_ELIMINA`(IN id VARCHAR(20))
BEGIN
  
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';
  
  IF EXISTS(SELECT * FROM slider WHERE SID=id) THEN
    DELETE FROM slider WHERE SID=id;    
    SELECT 1;
  ELSE
    SELECT 98;
  END IF;
  
END;
