
-- CALL SP_ELIMINA_HEAD_SERVICIO(3);   
-- SELECT * FROM SERVICIO;

DROP PROCEDURE IF EXISTS bodyflex.SP_ELIMINA_HEAD_SERVICIO;
CREATE PROCEDURE bodyflex.`SP_ELIMINA_HEAD_SERVICIO`(IN id VARCHAR(20))
BEGIN
  
    DELETE FROM DETALLE_SERVICIO WHERE SEID=id;    
    DELETE FROM SERVICIO WHERE SEID=id;    
    SELECT 1;
          
END;
