
-- CALL SP_CONSULTA_CATEGORIA_FORM_PUBLICACION();
-- select * from 


DROP PROCEDURE IF EXISTS bodyflex.SP_CONSULTA_CATEGORIA_FORM_PUBLICACION;
CREATE PROCEDURE bodyflex.`SP_CONSULTA_CATEGORIA_FORM_PUBLICACION`()
BEGIN

  SELECT DISTINCT CATETINOM 
  FROM PUBLICACION_ETIQUETA
  ORDER BY CATETINOM ASC;

END;
