
-- SP_PUBLICACION_CONSULTA_REFERENCIA();

DROP PROCEDURE IF EXISTS bodyflex.SP_PUBLICACION_CONSULTA_REFERENCIA;
CREATE PROCEDURE bodyflex.`SP_PUBLICACION_CONSULTA_REFERENCIA`()
BEGIN

    SELECT RETIPO
    FROM REFERENCIA 
    ORDER BY REID ASC;
      
END;


-- select * from REFERENCIA
-- DELETE from REFERENCIA
-- SELECT * FROM publicacion_referencia


