
-- CALL SP_PUBLICACION_CONSULTA_CATEGORIA_ETIQUETA();
-- SELECT * FROM PROFESIONAL;
-- SELECT * FROM CATEGORIA_ETIQUETA;


DROP PROCEDURE IF EXISTS bodyflex.SP_PUBLICACION_CONSULTA_CATEGORIA_ETIQUETA;
CREATE PROCEDURE bodyflex.`SP_PUBLICACION_CONSULTA_CATEGORIA_ETIQUETA`()
BEGIN

DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';

  IF EXISTS(SELECT * FROM PUBLICACION_CATEGORIA_ETIQUETA) THEN
      SELECT CATETINOM
      FROM PUBLICACION_CATEGORIA_ETIQUETA
      ORDER BY CATETINOM ASC;
  ELSE
    SELECT 98;
  END IF;

END




