
-- CALL SP_ELIMINA_SLIDER('12');
   
-- SELECT * FROM SLIDER;

DROP PROCEDURE IF EXISTS bodyflex.SP_ELIMINA_SLIDER;
CREATE PROCEDURE bodyflex.`SP_ELIMINA_SLIDER`(IN id VARCHAR(20))
BEGIN
  
  SET @ARCHIVO = 0;
  SET @POSIMG=0;
  
  IF EXISTS(SELECT * FROM slider WHERE SID=id) THEN
    SET @ARCHIVO = (SELECT SNOMIMG FROM slider WHERE SID=id);
    SET @POSIMG = (SELECT SPOSIMG FROM slider WHERE SID=id);
    DELETE FROM slider WHERE SID=id;    
    SELECT 1, @ARCHIVO, @POSIMG;
  ELSE
    SELECT 0, @ARCHIVO, @POSIMG;
  END IF;
  
END;
