-- CALL SP_CONSULTA_CATEGORIA_FORM_PUBLICACION('');
-- CALL SP_CONSULTA_CATEGORIA_FORM_PUBLICACION('1');

DROP PROCEDURE IF EXISTS bodyflex.SP_CONSULTA_CATEGORIA_FORM_PUBLICACION;
CREATE PROCEDURE bodyflex.`SP_CONSULTA_CATEGORIA_FORM_PUBLICACION`(IN keyWord VARCHAR(500))
BEGIN

  DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';
  IF EXISTS(SELECT DISTINCT CATETINOM FROM PUBLICACION_ETIQUETA PE WHERE CATETINOM LIKE CONCAT('%',keyWord,'%')) THEN 
      SELECT DISTINCT CATETINOM 
      FROM PUBLICACION_ETIQUETA PE
      WHERE CATETINOM LIKE CONCAT('%',keyWord,'%')
      ORDER BY PE.CATETINOM ASC;
  ELSE
    SELECT 98, keyWord;
  END IF;

END;


-- SELECT * FROM PUBLICACION_ETIQUETA