
-- SP_CONSULTA_CURRICULUM('13661574');
-- SELECT * FROM CURRICULUM;

DROP PROCEDURE IF EXISTS bodyflex.SP_CONSULTA_CURRICULUM;
CREATE PROCEDURE bodyflex.`SP_CONSULTA_CURRICULUM`(IN rut VARCHAR(20))
BEGIN

    SELECT CURID
    , CURFECING
    , CURFECMOD
    , CURTIT
    , CURDES 
    FROM CURRICULUM 
    WHERE PRUT=rut;
      
END;




