
-- SELECT * FROM PUBLICACION_REFERENCIA
-- SELECT * FROM PUBLICACION


DROP PROCEDURE IF EXISTS bodyflex.SP_PUBLICACION_VERIFICA_ELEMENTOS;
CREATE PROCEDURE bodyflex.`SP_PUBLICACION_VERIFICA_ELEMENTOS`(IN id VARCHAR(50))
BEGIN

DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';

  SET @REFERENCIAS=0;
  SET @ETIQUETAS=0;

  IF EXISTS(SELECT PRID FROM PUBLICACION_REFERENCIA WHERE PUID=id) THEN
    SET @REFERENCIAS=1;
    IF EXISTS(SELECT PEID FROM PUBLICACION_ETIQUETA WHERE PUID=id) THEN
      SET @ETIQUETAS=1;
    ELSE
      SET @ETIQUETAS=0;
    END IF;
  ELSE
    SET @REFERENCIAS=0;
    IF EXISTS(SELECT PEID FROM PUBLICACION_ETIQUETA WHERE PUID=id) THEN
      SET @ETIQUETAS=1;
    ELSE
      SET @ETIQUETAS=0;
    END IF;
  END IF;  
    
  IF @REFERENCIAS=1 AND @ETIQUETAS=1 THEN
    SELECT 1 AS 'RESP', 'POSEE ETIQUETAS Y REFERENCIAS' AS 'DESC'; -- POSEE ETIQUETAS Y REFERENCIAS
  END IF;
  IF @REFERENCIAS=1 AND @ETIQUETAS=0 THEN
    SELECT 2 AS 'RESP', 'POSEE REFERENCIAS, NO POSEE ETIQUETAS' AS 'DESC'; -- POSEE REFERENCIAS, NO POSEE ETIQUETAS
  END IF;
  IF @REFERENCIAS=0 AND @ETIQUETAS=1 THEN
    SELECT 3 AS 'RESP', 'NO POSEE REFERENCIAS, POSEE ETIQUETAS' AS 'DESC'; -- NO POSEE REFERENCIAS, POSEE ETIQUETAS
  END IF;
  IF @REFERENCIAS=0 AND @ETIQUETAS=0 THEN
    SELECT 4 AS 'RESP', 'NO POSEE REFERENCIAS, NO POSEE ETIQUETAS' AS 'DESC'; -- NO POSEE REFERENCIAS, NO POSEE ETIQUETAS
  END IF;
   
    
END;
