-- CALL SP_PUBLICACION_CONSULTA_ETIQUETA2('CATEGORIA1');
-- CALL SP_PUBLICACION_CONSULTA_ETIQUETA2('CATEGORIA2');


DROP PROCEDURE IF EXISTS bodyflex.SP_PUBLICACION_CONSULTA_ETIQUETA2;
CREATE PROCEDURE bodyflex.`SP_PUBLICACION_CONSULTA_ETIQUETA2`( 
                                                                IN cat VARCHAR(50)
                                                            )
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';

  IF EXISTS(SELECT * FROM ETIQUETA WHERE CATETINOM=cat)THEN

    SELECT ETNOM
    , CATETINOM
    FROM PUBLICACION_LIST_ETIQUETAS
    WHERE CATETINOM = cat
    ORDER BY ETNOM ASC;
  
  ELSE
    SELECT 98;
  END IF;      
      
END;

-- SELECT * FROM ETIQUETA