-- CALL SP_ELIMINA_PUBLICACION('35');
   
-- SELECT * FROM PUBLICACION;

DROP PROCEDURE IF EXISTS bodyflex.SP_ELIMINA_PUBLICACION;
CREATE PROCEDURE bodyflex.`SP_ELIMINA_PUBLICACION`(IN id VARCHAR(20))
BEGIN
  
    DELETE FROM PUBLICACION_REFERENCIA WHERE PUID=id;
    DELETE FROM PUBLICACION_ETIQUETA WHERE PUID=id;
    DELETE FROM VOTACION WHERE PUID=id;
    DELETE FROM PUBLICACION WHERE PUID=id;    
    SELECT 1;
          
END;
