-- CALL SP_PROFESIONAL_ELIMINA_PRODUCTO('25');
-- SELECT * FROM PROFESIONAL_PRODUCTO;

DROP PROCEDURE IF EXISTS bodyflex.SP_PROFESIONAL_ELIMINA_PRODUCTO;
CREATE PROCEDURE bodyflex.`SP_PROFESIONAL_ELIMINA_PRODUCTO`(IN id VARCHAR(20))
BEGIN

DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';
    
  UPDATE PROFESIONAL_PRODUCTO SET PROPEST='ELIMINADO' WHERE proPID=id;    
  SELECT 1;

END;
