-- CALL SP_PERFIL_PROFESIONAL_GET_PRESENTACION('9386703');
-- SELECT * FROM PROFESIONAL;
-- SELECT * FROM OTRO;

DROP PROCEDURE IF EXISTS bodyflex.SP_PERFIL_PROFESIONAL_GET_PRESENTACION;
CREATE PROCEDURE bodyflex.`SP_PERFIL_PROFESIONAL_GET_PRESENTACION`(IN rut VARCHAR(20))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';

  IF EXISTS(SELECT * FROM PROFESIONAL WHERE PRUT = rut) THEN
    
    SET @URL = (SELECT PARVAL FROM PARAMETROS WHERE PARNOM='DRIVE');
    
    SELECT P.PFOTOPRE
    , P.PTXTOPRE
    , CONCAT(P.PNOM1, ' ', P.PNOM2, ' ', P.PAPE1, ' ', P.PAPE2) AS NOMBRE
    , @URL AS URL
    , P.PMAIL AS MAIL
    FROM PROFESIONAL P
    WHERE PRUT=rut;
  ELSE
    SELECT 98;    
  END IF;
  
END




