-- CALL SP_CONSULTA_COMENTARIOS_PUBLICACION(35);
-- SELECT * FROM PROFESIONAL;
-- SELECT * FROM usuario;
-- SELECT * FROM COMENTARIO_PUBLICACION
-- SELECT * FROM PUBLICACION

DROP PROCEDURE IF EXISTS bodyflex.SP_CONSULTA_COMENTARIOS_PUBLICACION;
CREATE PROCEDURE bodyflex.`SP_CONSULTA_COMENTARIOS_PUBLICACION`(
                                                              IN id VARCHAR(20)
                                                            )
BEGIN

    SELECT CP.CPID
    , CASE CP.cpPer
        WHEN 1 THEN (SELECT P.PNOM1 FROM PROFESIONAL P WHERE P.PRUT=CP.PRUT)
        WHEN 2 THEN (SELECT U.UNOMBRE FROM USUARIO U WHERE U.UMAIL=CP.UMAIL)
      END AS 'NOMBRE'
    , CASE CP.cpPer
        WHEN 1 THEN (SELECT P.PAPE1 FROM PROFESIONAL P WHERE P.PRUT=CP.PRUT)
        WHEN 2 THEN (SELECT U.UAPELLIDO FROM USUARIO U WHERE U.UMAIL=CP.UMAIL)
      END AS 'APELLIDO'
    , DATE_FORMAT(CP.CPFEC,'%b %d %Y %h:%i %p') AS FECHA
    , CP.CPDET AS COMENTARIO
    , CP.CPTIP AS TIPO
  FROM COMENTARIO_PUBLICACION CP 
  WHERE PUID=id 
  ORDER BY CPORD ASC;
  
END




