
-- SP_PUBLICACION_CONSULTA_REFERENCIA();

DROP PROCEDURE IF EXISTS bodyflex.SP_PUBLICACION_CONSULTA_REFERENCIA;
CREATE PROCEDURE bodyflex.`SP_PUBLICACION_CONSULTA_REFERENCIA`()
BEGIN

DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';

  IF EXISTS(SELECT * FROM PUBLICACION_LIST_REFERENCIA) THEN 
    SELECT RETIPO FROM PUBLICACION_LIST_REFERENCIA ORDER BY REID ASC;
  ELSE
    SELECT 98;
  END IF;    
  
END;


-- select * from REFERENCIA
-- DELETE from REFERENCIA
-- SELECT * FROM publicacion_referencia


