-- CALL SP_PUBLICACION_ELIMINA('27');
   
-- SELECT * FROM PUBLICACION;

DROP PROCEDURE IF EXISTS bodyflex.SP_PUBLICACION_ELIMINA;
CREATE PROCEDURE bodyflex.`SP_PUBLICACION_ELIMINA`(IN id VARCHAR(20))
BEGIN
  
  DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';
  SET @SW=0;
  
  IF EXISTS(SELECT * FROM PUBLICACION_COMENTARIO WHERE PUID=id) THEN
    SET @SW=1;
  END IF;
  IF EXISTS(SELECT * FROM PUBLICACION_VOTACION WHERE PUID=id) THEN
    SET @SW=1;
  END IF;
  IF EXISTS(SELECT * FROM PUBLICACION_DENUNCIA WHERE PUID=id) THEN
    SET @SW=1;
  END IF;
  IF EXISTS(SELECT * FROM PUBLICACION_VISITAS WHERE PUID=id) THEN
    SET @SW=1;
  END IF;
  
  -- SELECT * FROM PUBLICACION 
  
  IF (@SW=1) THEN
    UPDATE PUBLICACION SET PUEST='INACTIVO' WHERE PUID=id;
  ELSE
    DELETE FROM PUBLICACION_ETIQUETA WHERE PUID=id;
    DELETE FROM PUBLICACION_REFERENCIA WHERE PUID=id;
    DELETE FROM PUBLICACION_PROFESIONAL WHERE PUID=id;
    DELETE FROM PUBLICACION_INTERNO WHERE PUID=id;
    DELETE FROM PUBLICACION_COMPLEMENTADOR WHERE PUID=id;
    
    
    IF (SELECT PUPOSIMG FROM PUBLICACION WHERE PUID=id) = 1 THEN
      SET @poseeImagen = (SELECT PUPOSIMG FROM PUBLICACION WHERE PUID=id);
    ELSE
      SET @poseeImagen = 0;
    END IF;
    
    DELETE FROM PUBLICACION WHERE PUID=id;
    
  END IF;
  
  SELECT 1, @poseeImagen;
           
END;
