
-- SELECT * FROM SERVICIO;

-- CALL SP_SERVICIO_PROFESIONAL_AGREGA(49, '9386703');
-- select * from PROFESIONAL_SERVICIO
-- select * from SERVICIO

DROP PROCEDURE IF EXISTS bodyflex.SP_SERVICIO_PROFESIONAL_AGREGA;
CREATE PROCEDURE bodyflex.`SP_SERVICIO_PROFESIONAL_AGREGA`( 
                                                IN id VARCHAR(20),
                                                IN rut VARCHAR(10)
                                              )
BEGIN

-- DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';  

    -- 1 DETERMINAR EXISTENCIA DEL REGISTRO
    IF (SELECT COUNT(*) FROM PROFESIONAL_SERVICIO WHERE SEID=id AND PRUT=rut)=0 THEN
      
      -- 2 INSERTAMOS REGISTRO
      INSERT INTO PROFESIONAL_SERVICIO(
        PRUT
        , SEID
      )VALUES(
        rut
        , id
      );
      
      -- 3 OBTENEMOS ULTIMO DPOID INGRESADO
      SET @id = (SELECT SEID FROM PROFESIONAL_SERVICIO WHERE PRUT=rut ORDER BY PSID DESC LIMIT 1);   
      
      -- SELECT * FROM SERVICIO
      
      -- 4 SELECCIONAMOS CAMPOS NECESARIOS
      SELECT PS.PSID AS PSID 
      , (SELECT S.SEID FROM SERVICIO S WHERE S.SEID=PS.SEID) AS SEID
      , (SELECT S.SENOM FROM SERVICIO S WHERE S.SEID=PS.SEID) AS SERNOM
      , (SELECT S.SEDESCOR FROM SERVICIO S WHERE S.SEID=PS.SEID) AS SEDESCOR
      , (SELECT S.SEDESLAR FROM SERVICIO S WHERE S.SEID=PS.SEID) AS SEDESLAR
      , id
      FROM PROFESIONAL_SERVICIO PS
      WHERE PRUT=rut
      ORDER BY PS.PSID;
    
    ELSE -- EL REGISTRO EXISTE  
      
      SELECT 98;
      
    END IF;
      
END;
