
-- CALL SP_ELIMINA_ETIQUETA('13661574','CATEGORIA5','CATEGORIA_X');
   
-- SELECT * FROM PROFESIONAL
-- SELECT * FROM CATEGORIA_ETIQUETA
-- SELECT * FROM ETIQUETA
-- SELECT * FROM PUBLICACION_ETIQUETA

DROP PROCEDURE IF EXISTS bodyflex.SP_ELIMINA_ETIQUETA;
CREATE PROCEDURE bodyflex.`SP_ELIMINA_ETIQUETA`( 
                                                    IN rut VARCHAR(20)
                                                  , IN cat VARCHAR(20)
                                                  , IN eti VARCHAR(50)
                                                )
BEGIN

    -- 1 DETERMINAR EXISTENCIA DEL REGISTRO
    IF EXISTS(SELECT ETNOM FROM ETIQUETA WHERE ETNOM=upper(eti) AND CATETINOM=UPPER(cat)) THEN
      IF NOT EXISTS(SELECT PEID FROM PUBLICACION_ETIQUETA WHERE ETNOM=eti)THEN    
          IF EXISTS(SELECT ETNOM FROM ETIQUETA WHERE ETNOM=upper(eti) AND CATETINOM=UPPER(cat) AND PRUT=rut) THEN
            DELETE FROM ETIQUETA WHERE CATETINOM=cat AND ETNOM=eti; 
            SELECT 1;
          ELSE
            SELECT 7; -- NO ES POSIBLE ELIMINAR UNA CATEGORÍA DE OTRO USUARIO
          END IF;
      ELSE
        SELECT 6; -- NO ES POSIBLE ELIMINAR PORQUE ETIQUETA SE ENCUENTRA EN PUBLICACION
      END IF;
    ELSE -- EL REGISTRO NO EXISTE  
      SELECT 8;      
    END IF;
      
END;
