-- CALL SP_ELIMINA_CURRICULUM_OTROS('25');
   
-- SELECT * FROM ESTUDIOS;

DROP PROCEDURE IF EXISTS bodyflex.SP_ELIMINA_CURRICULUM_OTROS;
CREATE PROCEDURE bodyflex.`SP_ELIMINA_CURRICULUM_OTROS`(IN id VARCHAR(20))
BEGIN
  
  IF EXISTS(SELECT * FROM OTRO WHERE OTID=id)THEN
    DELETE FROM OTRO WHERE OTID=id;    
    SELECT 1;
  ELSE
    SELECT 0;
  END IF;
  
END;
