
-- CALL SP_PROFESIONAL_PRODUCTO_CONSULTA_CONTENIDO(150,@corErr);

-- CALL SP_PROFESIONAL_PRODUCTO_CONSULTA_CONTENIDO(25,@corErr);
-- SELECT @corErr AS corErr;

-- CALL SP_PROFESIONAL_PRODUCTO_CONSULTA_CONTENIDO(23,@corErr);
-- SELECT @corErr AS corErr;

-- SELECT * FROM PROFESIONAL_PRODUCTO_CONTENIDO

-- CALL SP_PROFESIONAL_PRODUCTO_CONSULTA_CONTENIDO(25);

DROP PROCEDURE IF EXISTS bodyflex.SP_PROFESIONAL_PRODUCTO_CONSULTA_CONTENIDO;
CREATE PROCEDURE bodyflex.`SP_PROFESIONAL_PRODUCTO_CONSULTA_CONTENIDO`(
  IN idPro INTEGER
  , OUT codErr INTEGER
)
BEGIN

DECLARE EXIT HANDLER FOR SQLEXCEPTION SET codErr=99;

SET codErr=0;

  IF EXISTS(SELECT * FROM PROFESIONAL_PRODUCTO_CONTENIDO WHERE proPID=idPro) THEN    
    SELECT PC.pco_id
    , PC.pco_tip
    , PC.pco_dri
    FROM PROFESIONAL_PRODUCTO_CONTENIDO PC,
    PROFESIONAL_PRODUCTO PP
    WHERE PP.PROPID=PC.PROPID AND (PP.PROPEST='PUBLICADO' OR PP.PROPEST='INGRESADO') AND PC.proPID=idPro
    ORDER BY PC.pco_id DESC;
  ELSE
    SET codErr=98;
  END IF;

END;
