
-- CALL SP_CONSULTA_ETIQUETA_FORM_PUBLICACION('?');
-- select * from 


DROP PROCEDURE IF EXISTS bodyflex.SP_CONSULTA_ETIQUETA_FORM_PUBLICACION;
CREATE PROCEDURE bodyflex.`SP_CONSULTA_ETIQUETA_FORM_PUBLICACION`(IN keyWord VARCHAR(500))
BEGIN

  DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';
  IF EXISTS(SELECT DISTINCT ETNOM FROM PUBLICACION_ETIQUETA WHERE ETNOM LIKE CONCAT('%',keyWord,'%')) THEN 
    SELECT DISTINCT ETNOM
    FROM PUBLICACION_ETIQUETA
    WHERE ETNOM LIKE CONCAT('%',keyWord,'%')
    ORDER BY ETNOM ASC;
  ELSE
    SELECT 98, keyWord;
  END IF;

END;
