-- CALL SP_PERFIL_PROFESIONAL_GET_SLIDER('9386703');
-- SELECT * FROM PROFESIONAL;
-- SELECT * FROM OTRO;

DROP PROCEDURE IF EXISTS bodyflex.SP_PERFIL_PROFESIONAL_GET_SLIDER;
CREATE PROCEDURE bodyflex.`SP_PERFIL_PROFESIONAL_GET_SLIDER`(IN rut VARCHAR(20))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';

  IF EXISTS(SELECT * FROM SLIDER WHERE PRUT = rut) THEN
    
    SET @URL = (SELECT PARVAL FROM PARAMETROS WHERE PARNOM='DRIVE');
    
    SELECT STIT1
    , SDES
    , SDFL
    , @URL AS URL
    FROM SLIDER
    WHERE PRUT=rut
    ORDER BY SPOS ASC;
  ELSE
    SELECT 98;    
  END IF;
  
END




