-- CALL SP_PERFIL_PROFESIONAL_GET_SERVICIOS('9386703');
-- SELECT * FROM PROFESIONAL;
-- SELECT * FROM PROFESIONAL_SERVICIO;
-- SELECT * FROM SERVICIO;

DROP PROCEDURE IF EXISTS bodyflex.SP_PERFIL_PROFESIONAL_GET_SERVICIOS;
CREATE PROCEDURE bodyflex.`SP_PERFIL_PROFESIONAL_GET_SERVICIOS`(IN rut VARCHAR(20))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';

  IF EXISTS(SELECT * FROM PROFESIONAL_SERVICIO WHERE PRUT = rut) THEN
        
    SELECT S.SEID
    , S.SENOM
    , S.SEIMGAWE
    , S.SEDESCOR
    FROM PROFESIONAL_SERVICIO PS, SERVICIO S
    WHERE PS.SEID = S.SEID AND PS.PRUT=rut
    ORDER BY PSID ASC;
    
  ELSE
    SELECT 98;    
  END IF;
  
END




