-- CALL SP_CONSULTA_PROF_FORM_PUBLICACION('a');
-- CALL SP_CONSULTA_PROF_FORM_PUBLICACION('A');
-- SELECT * FROM PROFESIONAL

DROP PROCEDURE IF EXISTS bodyflex.SP_CONSULTA_PROF_FORM_PUBLICACION;
CREATE PROCEDURE bodyflex.`SP_CONSULTA_PROF_FORM_PUBLICACION`(IN keyWord VARCHAR(500))
BEGIN

  DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';
  IF EXISTS(SELECT * FROM PROFESIONAL WHERE PNOM1 LIKE CONCAT('%',keyWord,'%') OR PNOM2 LIKE CONCAT('%',keyWord,'%') OR PAPE1 LIKE CONCAT('%',keyWord,'%') OR PAPE2 LIKE CONCAT('%',keyWord,'%')) THEN
    
    SELECT CONCAT(UPPER(PNOM1),' ',UPPER(PNOM2),' ',UPPER(PAPE1),' ',UPPER(PAPE2)) AS NOMBRE
    , PRUT
    FROM PROFESIONAL
    WHERE PNOM1 LIKE CONCAT('%',keyWord,'%') 
    OR PNOM2 LIKE CONCAT('%',keyWord,'%')
    OR PAPE1 LIKE CONCAT('%',keyWord,'%')
    OR PAPE2 LIKE CONCAT('%',keyWord,'%');
    
  ELSE
    SELECT 98, keyWord;
  END IF;
  
END;
