
-- select * from servicio
-- select * from profesional

-- CALL SP_SERVICIO_PROFESIONAL_OBTIENE_TODOS(9386703);

DROP PROCEDURE IF EXISTS bodyflex.SP_SERVICIO_PROFESIONAL_OBTIENE_TODOS;
CREATE PROCEDURE bodyflex.`SP_SERVICIO_PROFESIONAL_OBTIENE_TODOS`(IN rut VARCHAR(10))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';  
  
  IF EXISTS(SELECT * FROM PROFESIONAL_SERVICIO WHERE PRUT=rut) THEN
  
    SET @CANT=(SELECT COUNT(*) FROM PROFESIONAL_SERVICIO);
    SELECT PS.PSID AS PSID 
      , (SELECT S.SEID FROM SERVICIO S WHERE S.SEID=PS.SEID) AS SEID
      , (SELECT S.SENOM FROM SERVICIO S WHERE S.SEID=PS.SEID) AS SERNOM
      , (SELECT S.SEDESCOR FROM SERVICIO S WHERE S.SEID=PS.SEID) AS SEDESCOR
      , (SELECT S.SEDESLAR FROM SERVICIO S WHERE S.SEID=PS.SEID) AS SEDESLAR
      , @CANT
      FROM PROFESIONAL_SERVICIO PS
      WHERE PRUT=rut
      ORDER BY PS.PSID;
  
  ELSE
  
    SELECT 98;    
  
  END IF;    
END;
