
-- SELECT * FROM DENUNCIA;

DROP PROCEDURE IF EXISTS bodyflex.SP_DENUNCIAR_PUBLICACION;
CREATE PROCEDURE bodyflex.`SP_DENUNCIAR_PUBLICACION`( 
                                      IN id VARCHAR(100)
                                      , IN sesion VARCHAR(100)
                                    )
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';
 
  IF EXISTS(SELECT * FROM PUBLICACION_DENUNCIA WHERE PUID=id AND DESE=sesion) THEN
    DELETE FROM PUBLICACION_DENUNCIA WHERE PUID=id AND DESE=sesion;
    SELECT 2;
  ELSE
    INSERT INTO PUBLICACION_DENUNCIA(PUID, DEFE, DESE) VALUES (id, now(), sesion);
    SELECT 1;
  END IF;

END;
