-- CALL SP_ELIMINA_CURRICULUM_ESTUDIOS('25');
   
-- SELECT * FROM ESTUDIOS;

DROP PROCEDURE IF EXISTS bodyflex.SP_ELIMINA_ESTUDIOS;
CREATE PROCEDURE bodyflex.`SP_ELIMINA_ESTUDIOS`(IN id VARCHAR(20))
BEGIN
  
  DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';
  DELETE FROM ESTUDIOS WHERE ESID=id;    
  SELECT 1;
          
END;
