
-- CALL SP_PORTAFOLIO_VERIFICA_IMAGEN('29');


DROP PROCEDURE IF EXISTS bodyflex.SP_PORTAFOLIO_VERIFICA_IMAGEN;
CREATE PROCEDURE bodyflex.`SP_PORTAFOLIO_VERIFICA_IMAGEN`( IN id VARCHAR(50) )
BEGIN

-- RETURN 1 = POSEE IMAGEN
-- RETURN 2 = NO SE ENCONTRO EL REGISTRO
-- RETURN 3 = NO POSEE IMAGEN 

  IF EXISTS(SELECT * FROM PORTAFOLIO WHERE POID=id)THEN
    SET @NOMIMG = (SELECT PONOMIMG FROM PORTAFOLIO WHERE POID=id);   
    IF @NOMIMG<>'NOIMAGEN' THEN 
      SELECT 1, @NOMIMG;
    ELSE
      SELECT 3, @NOMIMG;
    END IF;
  ELSE
    SELECT 2, '';
  END IF;
      
END;


-- SELECT * FROM SLIDER;