-- call SP_CONSULTA_TITULO_PUBLICACION('');
-- call SP_CONSULTA_TITULO_PUBLICACION('A');
-- call SP_CONSULTA_TITULO_PUBLICACION('H');
-- call SP_CONSULTA_TITULO_PUBLICACION('R');
-- call SP_CONSULTA_TITULO_PUBLICACION('T');
-- call SP_CONSULTA_TITULO_PUBLICACION('W');
-- call SP_CONSULTA_TITULO_PUBLICACION('Y');

DROP PROCEDURE IF EXISTS bodyflex.SP_CONSULTA_TITULO_PUBLICACION;
CREATE PROCEDURE bodyflex.`SP_CONSULTA_TITULO_PUBLICACION`(IN keyWord VARCHAR(1000))
BEGIN

DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';

  IF EXISTS(SELECT * FROM PUBLICACION P WHERE P.PUEST='PUBLICADA' AND P.PUTITULO LIKE CONCAT('%',keyWord,'%')) THEN
      SELECT PUTITULO
      , PUID
      FROM PUBLICACION P
      WHERE P.PUEST='PUBLICADA'
      AND P.PUTITULO LIKE CONCAT('%',keyWord,'%')  
      ORDER BY P.PUTITULO;
  ELSE
    SELECT 98, keyWord;
  END IF;
  
END



-- select * from publicacion
