
-- CALL SP_CONSULTA_S1();
   
-- SELECT * FROM SECCION1;

DROP PROCEDURE IF EXISTS bodyflex.SP_CONSULTA_S1;
CREATE PROCEDURE bodyflex.`SP_CONSULTA_S1`()
BEGIN

    SELECT * 
    FROM SECCION1 
    ORDER BY ESTS1 DESC;
      
END;
