
-- CALL SP_PRESENTACION_VERIFICA_IMAGEN('13661574');


DROP PROCEDURE IF EXISTS bodyflex.SP_PRESENTACION_VERIFICA_IMAGEN;
CREATE PROCEDURE bodyflex.`SP_PRESENTACION_VERIFICA_IMAGEN`( IN rut VARCHAR(10) )
BEGIN

  set @foto = (SELECT PFOTOPRE FROM PROFESIONAL WHERE PRUT=rut);
  IF NOT ISNULL(@foto) THEN
    SELECT 1, @foto;
  ELSE
    SELECT 2, '';
  END IF;
      
END;


-- SELECT * FROM PROFESIONAL;