-- CALL SP_PERFIL_PROFESIONAL_GET_RSM_CURRICULUM('9386703');
-- SELECT * FROM PROFESIONAL;
-- SELECT * FROM ESTUDIOS;

DROP PROCEDURE IF EXISTS bodyflex.SP_PERFIL_PROFESIONAL_GET_RSM_CURRICULUM;
CREATE PROCEDURE bodyflex.`SP_PERFIL_PROFESIONAL_GET_RSM_CURRICULUM`(IN rut VARCHAR(20))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';

  IF EXISTS(SELECT * FROM ESTUDIOS WHERE PRUT = rut) THEN
    
    SET @URL = (SELECT PARVAL FROM PARAMETROS WHERE PARNOM='DRIVE');
    SET @fotPre = (SELECT P.PFOTOPRE FROM PROFESIONAL P WHERE P.PRUT=rut);
    SET @nom = (SELECT CONCAT(PNOM1,' ',PNOM2,' ',PAPE1,' ',PAPE2) FROM PROFESIONAL WHERE PRUT=rut);
    
    SELECT ESNOM
    , @nom AS 'NOMPRO'
    , @fotPre AS 'FOTPRE'
    , @URL AS 'URL'
    FROM ESTUDIOS
    WHERE PRUT=rut
    ORDER BY ESPOS ASC
    LIMIT 4;
    
  ELSE
    SELECT 98;    
  END IF;
  
END




