
-- select * from servicio

-- CALL SP_SERVICIO_OBTIENE_DETALLE(49);

DROP PROCEDURE IF EXISTS bodyflex.SP_SERVICIO_OBTIENE_DETALLE;
CREATE PROCEDURE bodyflex.`SP_SERVICIO_OBTIENE_DETALLE`(IN id VARCHAR(10))
BEGIN

DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';    
  
    SET @CANT=(SELECT COUNT(*) FROM SERVICIO);
    SELECT SEID
      , SENOM
      , SEDESCOR
      , SEDESLAR
      , SEIMGAWE
      , SEIMGSER
      , SEIDFLI
      , @CANT
      FROM SERVICIO
      WHERE SEID=id
      ORDER BY SEID DESC;

END;
