
-- select * from publicacion_referencia

-- CALL SP_PUBLICACION_CONSULTA_CONTENIDO(9);

DROP PROCEDURE IF EXISTS bodyflex.SP_PUBLICACION_CONSULTA_CONTENIDO;
CREATE PROCEDURE bodyflex.`SP_PUBLICACION_CONSULTA_CONTENIDO`(IN idPub INTEGER)
BEGIN

DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';

    IF EXISTS(SELECT * FROM PUBLICACION_CONTENIDO P WHERE P.PUID=idPub) THEN    

      SELECT PC.idCont
      , PC.tipCont
      , PC.urlCont
      FROM PUBLICACION_CONTENIDO PC WHERE PC.PUID=idPub
      ORDER BY PC.idCont ASC;
      
    ELSE
    
      SELECT 98;
    
    END IF;
END;
