-- call SP_CONSULTA_ETIQUETA_PUBLICACION_RSM('72');
-- call SP_CONSULTA_ETIQUETA_PUBLICACION_RSM('107');

DROP PROCEDURE IF EXISTS bodyflex.SP_CONSULTA_ETIQUETA_PUBLICACION_RSM;
CREATE PROCEDURE bodyflex.`SP_CONSULTA_ETIQUETA_PUBLICACION_RSM`(IN id VARCHAR(100))
BEGIN

  SELECT ETNOM FROM PUBLICACION_ETIQUETA WHERE PUID=id;
    
END



-- select * from PUBLICACION_ETIQUETA
