-- CALL SP_CONSULTA_CURRICULUM_EXPERIENCIA('13661574');
-- SELECT * FROM PROFESIONAL;
-- SELECT * FROM CURRICULUM;
-- SELECT * FROM EXPERIENCIA;

DROP PROCEDURE IF EXISTS bodyflex.SP_CONSULTA_CURRICULUM_EXPERIENCIA;
CREATE PROCEDURE bodyflex.`SP_CONSULTA_CURRICULUM_EXPERIENCIA`(
                                                              IN rut VARCHAR(20)
                                                            )
BEGIN

  IF EXISTS(SELECT CURID FROM CURRICULUM c WHERE c.PRUT = rut) THEN
  
      SET @idCur = (SELECT CURID FROM CURRICULUM c WHERE c.PRUT = rut); -- DEBERIA EXISTIR SOLO UN REGISTRO
      
      SELECT EXID
      , EXCARGO
      , EXINS
      , EXFECDES
      , EXFECHAS
      , EXIMG
      , EXDES
      FROM EXPERIENCIA
      WHERE CURID=@idCur
      ORDER BY EXFECHAS DESC;
      
  ELSE
    -- PRIMERO DEBE INGRESAR CURRÍCULUM PARA POSTERIORMENTE AGREGAR ESTUDIOS
    SELECT 8;    
    
  END IF;
  
END




