
-- CALL SP_CONSULTA_CATEGORIA_ETIQUETA();
-- SELECT * FROM PROFESIONAL;
-- SELECT * FROM CATEGORIA_ETIQUETA;


DROP PROCEDURE IF EXISTS bodyflex.SP_CONSULTA_CATEGORIA_ETIQUETA;
CREATE PROCEDURE bodyflex.`SP_CONSULTA_CATEGORIA_ETIQUETA`()
BEGIN

    SELECT CATETINOM
    FROM CATEGORIA_ETIQUETA
    ORDER BY CATETINOM ASC;
    
END




