
-- CALL SP_PUBLICACION_POSEE_CONTENIDO('86');

-- SELECT * FROM PUBLICACION_CONTENIDO;

DROP PROCEDURE IF EXISTS bodyflex.SP_PUBLICACION_POSEE_CONTENIDO;
CREATE PROCEDURE bodyflex.`SP_PUBLICACION_POSEE_CONTENIDO`(
                                                  IN id VARCHAR(50)
                                                 )
BEGIN

DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';
  IF EXISTS(SELECT * FROM PUBLICACION_CONTENIDO WHERE PUID=id)THEN
      SET @registros = (SELECT COUNT(*) FROM PUBLICACION_CONTENIDO WHERE PUID=id);
      IF @registros>1 THEN
        SELECT 1;
      ELSE
        SELECT 0;
      END IF;  
  ELSE
    SELECT 98;
  END IF;

END




