
-- CALL SP_PROFESIONAL_GET_CANT_PRODUCTOS_CART('482v425q6ofr79enp27na39ii0');
-- CALL SP_PROFESIONAL_GET_CANT_PRODUCTOS_CART('e5cvpmjqp8ui40t81rjk9v8e41');
-- CALL SP_PROFESIONAL_GET_CANT_PRODUCTOS_CART('3g5q3kaiuunsr89agmm7tfkdj2');

DROP PROCEDURE IF EXISTS bodyflex.SP_PROFESIONAL_GET_CANT_PRODUCTOS_CART;
CREATE PROCEDURE bodyflex.`SP_PROFESIONAL_GET_CANT_PRODUCTOS_CART`(
                                                                IN se VARCHAR(50)
                                                              )
BEGIN

DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';
  
  IF EXISTS(
  
    SELECT *
    FROM CARRO C, CARRO_DETALLE CD 
    WHERE C.CAID=CD.CAID AND C.CASESION =se
  
  ) THEN
  
    SELECT SUM(CD.CAD_CAN) AS NUM_PRO
    FROM CARRO C, CARRO_DETALLE CD 
    WHERE C.CAID=CD.CAID AND C.CASESION =se;
  
  ELSE
    
    SELECT 0 AS NUM_PRO;
    
  END IF;
      
END








