-- CALL SP_ELIMINA_CURRICULUM_OTROS('25');
   
-- SELECT * FROM ESTUDIOS;

DROP PROCEDURE IF EXISTS bodyflex.SP_OTROS_ELIMINA;
CREATE PROCEDURE bodyflex.`SP_OTROS_ELIMINA`(IN id VARCHAR(20))
BEGIN

DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';
  
  
    DELETE FROM OTROS WHERE OTID=id;    
    SELECT 1;
  
  
END;
