
-- CALL SP_PUBLICACION_INGRESA_CATEGORIA_ETIQUETA('13661574','PEO');
-- CALL SP_PUBLICACION_INGRESA_CATEGORIA_ETIQUETA('13661574','FITNESS');
-- CALL SP_PUBLICACION_INGRESA_CATEGORIA_ETIQUETA('13661574','fitness');
-- CALL SP_PUBLICACION_INGRESA_CATEGORIA_ETIQUETA('13661574','OTRA');
   
-- SELECT * FROM PROFESIONAL
-- SELECT * FROM PUBLICACION_CATEGORIA_ETIQUETA
-- SELECT * FROM PUBLICACION_LIST_ETIQUETAS

DROP PROCEDURE IF EXISTS bodyflex.SP_PUBLICACION_INGRESA_CATEGORIA_ETIQUETA;
CREATE PROCEDURE bodyflex.`SP_PUBLICACION_INGRESA_CATEGORIA_ETIQUETA`( 
                                                                IN rut VARCHAR(20)
                                                              , IN cat VARCHAR(50)
                                                            )
BEGIN
-- DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';

    -- 1 DETERMINAR EXISTENCIA DEL REGISTRO
    IF NOT EXISTS(SELECT CATETINOM FROM PUBLICACION_CATEGORIA_ETIQUETA WHERE CATETINOM=upper(cat)) THEN

      -- 2 INSERTAMOS REGISTRO
      
      INSERT INTO PUBLICACION_CATEGORIA_ETIQUETA(
        CATRUT
      , CATETINOM
      )VALUES(
        rut
        , UPPER(cat)
      );
      
      
      SELECT 1;
    
      -- select 0;
    
    ELSE -- EL REGISTRO EXISTE  
      SELECT 98;      
    END IF;
      
END;
