
-- CALL SP_CONSULTA_SLIDER('13661574');
   
-- SELECT * FROM SLIDER;

DROP PROCEDURE IF EXISTS bodyflex.SP_CONSULTA_SLIDER;
CREATE PROCEDURE bodyflex.`SP_CONSULTA_SLIDER`(IN rut VARCHAR(20))
BEGIN

    SET @CANT=(SELECT COUNT(*) FROM SLIDER WHERE PRUT=rut);
    SELECT SID
    , STIT1
    , STIT2
    , SDES
    , SPOS
    , SDFL 
    , @CANT AS 'CANT'
    FROM slider 
    WHERE prut=rut;
      
END;
