-- CALL SP_PERFIL_PROFESIONAL_GET_DATA_PUBLICACION(80);
-- SELECT * FROM PROFESIONAL;
-- SELECT * FROM PROFESIONAL_SERVICIO;
-- SELECT * FROM PUBLICACION;
-- SELECT * FROM PUBLICACION_PROFESIONAL;

DROP PROCEDURE IF EXISTS bodyflex.SP_PERFIL_PROFESIONAL_GET_DATA_PUBLICACION;
CREATE PROCEDURE bodyflex.`SP_PERFIL_PROFESIONAL_GET_DATA_PUBLICACION`(
                                                                    IN id VARCHAR(20)
                                                                  )
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';

    SET @URL = (SELECT PARVAL FROM PARAMETROS WHERE PARNOM='DRIVE');
    IF EXISTS(SELECT * FROM PUBLICACION WHERE PUID=id) THEN    
      SELECT P.PUID
      , DATE_FORMAT(P.PUFEPUB,'%m-%d-%Y') AS PUFEPUB
      , P.PUTITULO
      , P.PUBAJ
      , P.PUIMG
      , @URL AS URL
      FROM PUBLICACION P
      WHERE P.PUID = id;
    ELSE
      SELECT 98;
    END IF;
    
END






