-- CALL SP_PERFIL_PROFESIONAL_GET_PORTAFOLIO(9386703);
-- SELECT * FROM PROFESIONAL;
-- SELECT * FROM PROFESIONAL_SERVICIO;
-- SELECT * FROM PORTAFOLIO;

DROP PROCEDURE IF EXISTS bodyflex.SP_PERFIL_PROFESIONAL_GET_PORTAFOLIO;
CREATE PROCEDURE bodyflex.`SP_PERFIL_PROFESIONAL_GET_PORTAFOLIO`(
                                                                    IN rut VARCHAR(20)
                                                                  )
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';

    SET @URL = (SELECT PARVAL FROM PARAMETROS WHERE PARNOM='DRIVE');
    IF EXISTS(SELECT * FROM PORTAFOLIO WHERE PRUT=rut) THEN    
      SELECT PONOMCAP
      , POIDFLI
      , @URL AS URL
      FROM PORTAFOLIO
      WHERE PRUT=rut
      ORDER BY POID ASC;
    ELSE
      SELECT 98;
    END IF;
END






