
-- CALL SP_MUESTRA_S1();
   
-- SELECT * FROM SLIDER;
-- ESTE SP ES EL QUE SELECCIONA Y MUESRA LOS VIGENTES AL VISITANTE

DROP PROCEDURE IF EXISTS bodyflex.SP_MUESTRA_S1;
CREATE PROCEDURE bodyflex.`SP_MUESTRA_S1`()
BEGIN

    SELECT * 
    FROM SECCION1 
    WHERE ESTS1=1
    ORDER BY PRIS1 ASC;
      
END;
