
-- CALL SP_CONSULTA_PRESENTACION('13661574');
-- SELECT * FROM PROFESIONAL WHERE PRUT='13661574';
-- SELECT PTXTOPRE FROM PROFESIONAL WHERE PRUT='13661574';

DROP PROCEDURE IF EXISTS bodyflex.SP_CONSULTA_PRESENTACION;
CREATE PROCEDURE bodyflex.`SP_CONSULTA_PRESENTACION`(IN rut VARCHAR(20))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';

  SET @texto=(SELECT PTXTOPRE FROM PROFESIONAL WHERE PRUT=rut);
  SET @texto=TRIM(IFNULL(@texto,'0'));

  IF @texto<>'0' and @texto<>'' THEN
    SELECT PFOTOPRE, PTXTOPRE FROM PROFESIONAL WHERE PRUT=rut;
  ELSE
    SELECT 98;
  END IF;
 
END;
