-- CALL SP_CUR_GET_OTR('9386703');
-- SELECT * FROM PROFESIONAL;
-- SELECT * FROM CURRICULUM;
-- SELECT * FROM EXPERIENCIA;
-- SELECT * FROM OTROS;
-- SELECT * FROM ESTUDIOS

DROP PROCEDURE IF EXISTS bodyflex.SP_CUR_GET_OTR;
CREATE PROCEDURE bodyflex.`SP_CUR_GET_OTR`(IN rut VARCHAR(20))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';

  IF EXISTS(SELECT * FROM OTROS WHERE PRUT = rut) THEN
       
      SELECT OTNOM
      , OTTIPO
      , DATE_FORMAT(OTFECHA,'%b %Y') AS OTFECHA
      , OTDES
      FROM OTROS
      WHERE PRUT = rut
      ORDER BY OTPOS ASC;
      
  ELSE
    
    SELECT 98;    
    
  END IF;
  
END




