-- CALL SP_EXPERIENCIA_ELIMINA('25');
   
-- SELECT * FROM ESTUDIOS;

DROP PROCEDURE IF EXISTS bodyflex.SP_EXPERIENCIA_ELIMINA;
CREATE PROCEDURE bodyflex.`SP_EXPERIENCIA_ELIMINA`(IN id VARCHAR(20))
BEGIN
  
  IF EXISTS(SELECT * FROM EXPERIENCIA WHERE EXID=id) THEN
    DELETE FROM EXPERIENCIA WHERE EXID=id;    
    SELECT 1;
  ELSE
    SELECT 0;
  END IF;
  
END;
