
-- CALL SP_CONSULTA_HEAD_SERVICIO('13661574');

-- SELECT * FROM PROFESIONAL;   
-- SELECT * FROM SERVICIO;

DROP PROCEDURE IF EXISTS bodyflex.SP_CONSULTA_HEAD_SERVICIO;
CREATE PROCEDURE bodyflex.`SP_CONSULTA_HEAD_SERVICIO`(IN rut VARCHAR(20))
BEGIN

    SELECT SEID, SETIT, SEPAR FROM SERVICIO WHERE prut=rut;
      
END;
