
-- CALL SP_CARRO_DEL_PROD('200');

-- select * from CARRO_DETALLE
-- select * from CARRO

DROP PROCEDURE IF EXISTS bodyflex.SP_CARRO_DEL_PROD;
CREATE PROCEDURE bodyflex.`SP_CARRO_DEL_PROD`( 
                                                IN vId VARCHAR(20)
                                              )
BEGIN

DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';
  
  IF EXISTS(SELECT * FROM CARRO_DETALLE WHERE CAD_ID=vId) THEN
    SET @ID = (SELECT CAID FROM CARRO_DETALLE WHERE CAD_ID=vId);
    DELETE FROM CARRO_DETALLE WHERE CAD_ID=vId;
    SET @PROVTA=IFNULL((SELECT SUM(CAD_CAN) FROM CARRO_DETALLE WHERE CAID=@ID),0);
    IF(@PROVTA=0)THEN
      DELETE FROM CARRO WHERE CAID=@ID;
      SET @PROVTA=0;
    END IF;
    SELECT 1, @PROVTA;
  ELSE
    SELECT 98;
  END IF;
      
END;



