-- CALL SP_PERFIL_PROFESIONAL_GET_PUBLICACIONES(9386703);
-- SELECT * FROM PROFESIONAL;
-- SELECT * FROM PROFESIONAL_SERVICIO;
-- SELECT * FROM PUBLICACION;
-- SELECT * FROM PUBLICACION_PROFESIONAL;

DROP PROCEDURE IF EXISTS bodyflex.SP_PERFIL_PROFESIONAL_GET_PUBLICACIONES;
CREATE PROCEDURE bodyflex.`SP_PERFIL_PROFESIONAL_GET_PUBLICACIONES`(
                                                                    IN rut VARCHAR(20)
                                                                  )
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT '99';

    SET @URL = (SELECT PARVAL FROM PARAMETROS WHERE PARNOM='DRIVE');
    IF EXISTS(SELECT * FROM PUBLICACION_PROFESIONAL WHERE PRUT=rut) THEN    
      SELECT P.PUID
      , DATE_FORMAT(P.PUFEPUB,'%m-%d-%Y') AS PUFEPUB
      , P.PUTITULO
      , P.PUBAJ
      , P.PUIMG
      , @URL AS URL
      FROM PUBLICACION P, PUBLICACION_PROFESIONAL PP
      WHERE PP.PUID=P.PUID AND PP.PRUT=rut AND P.PUEST='PUBLICADA'
      ORDER BY P.PUID ASC;
    ELSE
      SELECT 98;
    END IF;
    
END






