-- SP_CONSULTA_HEAD_PORTAFOLIO


-- CALL SP_CONSULTA_HEAD_PORTAFOLIO('13661574');

-- SELECT * FROM PROFESIONAL
-- SELECT * FROM PORTAFOLIO;   


DROP PROCEDURE IF EXISTS bodyflex.SP_CONSULTA_HEAD_PORTAFOLIO;
CREATE PROCEDURE bodyflex.`SP_CONSULTA_HEAD_PORTAFOLIO`(IN rut VARCHAR(20))
BEGIN

    SELECT POID, POTIT, POPA FROM PORTAFOLIO WHERE prut=rut;
      
END;
