
-- CALL SP_PUBLICACION_CONSULTA_ETIQUETA('CATEGORIA1','');
-- CALL SP_PUBLICACION_CONSULTA_ETIQUETA('CATEGORIA2','');
-- CALL SP_PUBLICACION_CONSULTA_ETIQUETA('CATEGORIA3','');
-- CALL SP_PUBLICACION_CONSULTA_ETIQUETA('CATEGORIA4','');
-- CALL SP_PUBLICACION_CONSULTA_ETIQUETA('CATEGORIA5','');

-- CALL SP_PUBLICACION_CONSULTA_ETIQUETA('A','XXX');
-- SELECT * FROM PROFESIONAL;
-- SELECT * FROM CATEGORIA_ETIQUETA;
-- SELECT * FROM ETIQUETA;

DROP PROCEDURE IF EXISTS bodyflex.SP_PUBLICACION_CONSULTA_ETIQUETA;
CREATE PROCEDURE bodyflex.`SP_PUBLICACION_CONSULTA_ETIQUETA`(
                                                  IN categ VARCHAR(50)
                                                  , IN query VARCHAR(50)
                                                 )
BEGIN

    SELECT ETNOM
    FROM ETIQUETA
    WHERE ETNOM LIKE CONCAT('%', query ,'%') AND CATETINOM = categ
    ORDER BY ETNOM ASC;
    
END




