
-- CALL SP_ELIMINA_HEAD_PORTAFOLIO(3);   
-- SELECT * FROM PORTAFOLIO;

DROP PROCEDURE IF EXISTS bodyflex.SP_ELIMINA_HEAD_PORTAFOLIO;
CREATE PROCEDURE bodyflex.`SP_ELIMINA_HEAD_PORTAFOLIO`(IN id VARCHAR(20))
BEGIN
  
    DELETE FROM DETALLE_PORTAFOLIO WHERE POID=id;    
    DELETE FROM PORTAFOLIO WHERE POID=id;    
    SELECT 1;
          
END;
