-- Drop table FUNCION
DROP TABLE IF EXISTS `FUNCION`;

CREATE TABLE `FUNCION` (
  `FUNCION_ID` int(11) NOT NULL,
  `MOD_ID` int(11) NOT NULL DEFAULT '0',
  `FUNCION_NOM` varchar(500) COMMENT 'NOMBRE FUNCION',
  `FUNCION_RES` varchar(50) COMMENT 'RESUMEN NOMBRE FUNCION',
  `FUNCION_DES` varchar(2000),
  `FUNCION_VIG` int(11) COMMENT 'VIGENCIA',
  `FUNCION_FOR` varchar(2000) COMMENT 'FORMULARIO, PÁGINA O NOMBRE DE MENÚ POR MEDIO DEL CUAL SE INTERACTUA CON LA FUNCIONALIDAD',
  `FUNCION_LID` int(11) COMMENT 'FUNCIÓN LIDER? 1=SI 0=NO',
  PRIMARY KEY(`FUNCION_ID`, `MOD_ID`),
  CONSTRAINT `Ref_68` FOREIGN KEY (`MOD_ID`)
    REFERENCES `MODULO`(`MOD_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE=INNODB;