-- Drop table TG_REGISTRO_ASISTENCIA
DROP TABLE IF EXISTS `TG_REGISTRO_ASISTENCIA`;

CREATE TABLE `TG_REGISTRO_ASISTENCIA` (
  `raID` int(11) NOT NULL AUTO_INCREMENT,
  `AN_RUT_NUM` int(11) NOT NULL DEFAULT '0',
  `raFecha` int(11),
  `raHoraLlegada` datetime,
  `raHoraSalida` datetime,
  `ra_Terminal` varchar(100),
  PRIMARY KEY(`raID`),
  CONSTRAINT `Ref_65` FOREIGN KEY (`AN_RUT_NUM`)
    REFERENCES `TM_ANALISTAS`(`AN_RUT_NUM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE=INNODB;