

SELECT * FROM TM_ANALISTAS

INSERT INTO TM_ANALISTAS (AN_CODIGO_ANALISTA, AN_NOMBRE_ANALISTA, AN_ROL_ANALISTA, aN_r) 
VALUES ('bipin90', 'Benjamin Ipinza', 1,1);

INSERT INTO TM_ANALISTAS (AN_CODIGO_ANALISTA, AN_NOMBRE_ANALISTA, AN_ROL_ANALISTA, aN_r) 
VALUES ('ggodo90', 'Gonzalo Godoy', 1,1);